"""
Choice API Routes - Domain-Specific Routes
============================================

CRUD, Query, and Intelligence factories are now registered via config in
choices_routes.py.  This file contains only manual domain-specific routes:
- Decision flow (decide, options, evaluate)
- Analytics and intelligence endpoints
"""

__version__ = "2.0"

from typing import Any

from fasthtml.common import Request

from adapters.inbound.auth import require_ownership_query
from adapters.inbound.boundary import boundary_handler
from core.ports.facade_protocols import ChoicesFacadeProtocol
from core.utils.result_simplified import Result


def create_choices_api_routes(
    app: Any,
    rt: Any,
    choice_service: ChoicesFacadeProtocol,
    **_kwargs: Any,
) -> list[Any]:
    """
    Create choice API routes that require domain-specific logic.

    CRUD, Query, and Intelligence routes are registered by register_domain_routes
    before this function is called (see choices_routes.py → CHOICES_CONFIG).

    Args:
        app: FastHTML application instance
        rt: Route decorator
        choice_service: ChoicesService instance (primary service)
        **_kwargs: Absorbs related services passed by register_domain_routes
    """

    # Service getter for ownership decorator (SKUEL012: named function, not lambda)
    def get_choice_service():
        return choice_service

    # ========================================================================
    # DOMAIN-SPECIFIC ROUTES (Manual)
    # ========================================================================
    # SECURITY: All UID-based routes verify user owns the choice before operating

    # NOTE: GET /api/choices/user/{user_uid} now generated by CommonQueryRouteFactory

    @rt("/api/choices/decide", methods=["POST"])
    @require_ownership_query(get_choice_service, uid_param="choice_uid")
    @boundary_handler(success_status=200)
    async def make_decision_route(request: Request, user_uid: str, entity: Any) -> Result[Any]:
        """Make a decision on a choice (requires ownership)."""
        body = await request.json()
        selected_option_uid = body.get("selected_option_uid")
        decision_rationale = body.get("decision_rationale")
        confidence_level = body.get("confidence_level", 0.8)

        # Validate request
        from core.models.ku.ku_request import KuChoiceDecisionRequest

        KuChoiceDecisionRequest.model_validate(
            {"selected_option_uid": selected_option_uid, "decision_rationale": decision_rationale}
        )

        # Use domain-specific make_decision method
        return await choice_service.make_decision(
            choice_uid=entity.uid,
            selected_option_uid=selected_option_uid,
            decision_rationale=decision_rationale,
            confidence=confidence_level,
        )

    @rt("/api/choices/options", methods=["POST"])
    @require_ownership_query(get_choice_service, uid_param="choice_uid")
    @boundary_handler(success_status=201)
    async def create_choice_option_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """Create a new option for a choice (requires ownership)."""
        body = await request.json()
        from core.models.ku.ku_request import KuChoiceOptionCreateRequest

        option_request = KuChoiceOptionCreateRequest.model_validate(body)

        # Use add_option method
        return await choice_service.add_option(
            choice_uid=entity.uid,
            title=option_request.title,
            description=option_request.description,
            feasibility_score=option_request.feasibility_score,
            risk_level=option_request.risk_level,
            potential_impact=option_request.potential_impact,
            resource_requirement=option_request.resource_requirement,
            estimated_duration=option_request.estimated_duration,
            dependencies=option_request.dependencies,
            tags=option_request.tags,
        )

    @rt("/api/choices/options/update", methods=["PUT"])
    @require_ownership_query(get_choice_service, uid_param="choice_uid")
    @boundary_handler()
    async def update_choice_option_route(
        request: Request, user_uid: str, entity: Any, option_uid: str
    ) -> Result[Any]:
        """Update a choice option (requires ownership)."""
        body = await request.json()

        from core.models.ku.ku_request import KuChoiceOptionUpdateRequest

        option_update = KuChoiceOptionUpdateRequest.model_validate(body)

        # Use update_option method
        return await choice_service.update_option(
            choice_uid=entity.uid,
            option_uid=option_uid,
            title=option_update.title,
            description=option_update.description,
            feasibility_score=option_update.feasibility_score,
            risk_level=option_update.risk_level,
            potential_impact=option_update.potential_impact,
            resource_requirement=option_update.resource_requirement,
            estimated_duration=option_update.estimated_duration,
            dependencies=option_update.dependencies,
            tags=option_update.tags,
        )

    @rt("/api/choices/evaluate", methods=["POST"])
    @require_ownership_query(get_choice_service, uid_param="choice_uid")
    @boundary_handler(success_status=200)
    async def evaluate_choice_outcome_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """Evaluate the outcome of a decided choice (requires ownership)."""
        body = await request.json()
        from core.models.ku.ku_request import KuChoiceEvaluationRequest

        evaluation_request = KuChoiceEvaluationRequest.model_validate(body)

        # Use evaluate_choice_outcome method from core service
        result: Result[Any] = await choice_service.core.evaluate_choice_outcome(
            choice_uid=entity.uid,
            evaluation=evaluation_request,
        )
        return result

    @rt("/api/choices/analytics")
    @boundary_handler()
    async def get_choice_analytics_route(request: Request, user_uid: str) -> Result[Any]:
        """Get choice analytics and decision patterns."""
        params = dict(request.query_params)

        timeframe = params.get("timeframe", "90d")

        # Parse timeframe to days
        lookback_days = 90
        if timeframe.endswith("d"):
            lookback_days = int(timeframe[:-1])

        # Use intelligence service (analytics methods consolidated here)
        result: Result[Any] = await choice_service.intelligence.get_decision_patterns(
            user_uid, days=lookback_days
        )
        return result

    # ========================================================================
    # INTELLIGENCE ROUTES (High-Value Analytics)
    # ========================================================================
    # These expose advanced intelligence methods not covered by IntelligenceRouteFactory

    @rt("/api/choices/intelligence/impact")
    @require_ownership_query(get_choice_service, uid_param="choice_uid")
    @boundary_handler()
    async def analyze_choice_impact_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """
        Analyze cross-domain impact of a decision.

        Query params:
            choice_uid: UID of choice to analyze (ownership verified)

        Returns:
            ChoiceImpactAnalysis with affected domains, relationships, and impact scores
        """
        result: Result[Any] = await choice_service.intelligence.analyze_choice_impact(entity.uid)
        return result

    @rt("/api/choices/intelligence/quality-correlations")
    @boundary_handler()
    async def get_quality_correlations_route(request: Request, user_uid: str) -> Result[Any]:
        """
        What factors correlate with good decisions?

        Analyzes user's past decisions to identify patterns that lead to
        positive vs negative outcomes.

        Returns:
            Dict with correlation scores for decision factors (confidence,
            principle alignment, time pressure, domain, etc.)
        """
        result: Result[Any] = await choice_service.intelligence.get_choice_quality_correlations(
            user_uid
        )
        return result

    @rt("/api/choices/intelligence/predict-quality")
    @require_ownership_query(get_choice_service, uid_param="choice_uid")
    @boundary_handler()
    async def predict_decision_quality_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """
        Predict quality of pending decision.

        Uses historical patterns to estimate likely outcome quality
        before making the decision.

        Query params:
            choice_uid: UID of pending choice (ownership verified)

        Returns:
            DecisionQualityPrediction with estimated quality score,
            confidence, and contributing factors
        """
        result: Result[Any] = await choice_service.intelligence.predict_decision_quality(
            entity.uid, user_uid
        )
        return result

    @rt("/api/choices/intelligence/domain-patterns")
    @boundary_handler()
    async def get_domain_decision_patterns_route(request: Request, user_uid: str) -> Result[Any]:
        """
        Get decision patterns by life domain.

        Analyzes how user makes decisions across different life domains
        (work, health, relationships, etc.).

        Query params:
            days (optional): Number of days to analyze (default: 90)

        Returns:
            Dict mapping domains to decision pattern metrics
        """
        params = dict(request.query_params)
        days = int(params.get("days", 90))

        result: Result[Any] = await choice_service.intelligence.get_domain_decision_patterns(
            user_uid, days=days
        )
        return result

    return []  # Routes registered via @rt() decorators (no objects returned)


# Export the route creation function
__all__ = ["create_choices_api_routes"]
