"""
Form Templates API - Lesson Linking Routes
============================================

Domain-specific routes for FormTemplate lesson embedding.
CRUD routes (create, get, list, update, delete) are generated by CRUDRouteFactory
via CRUDRouteConfig in form_templates_routes.py.
"""

from typing import TYPE_CHECKING, Any

from fasthtml.common import Request

from adapters.inbound.auth import make_service_getter, require_admin
from adapters.inbound.boundary import boundary_handler
from adapters.inbound.form_helpers import parse_json_body
from core.models.forms.form_template_request import FormLessonLinkRequest
from core.utils.logging import get_logger
from core.utils.result_simplified import Result

if TYPE_CHECKING:
    from core.services.forms.form_template_service import FormTemplateService

logger = get_logger(__name__)


def create_form_templates_api_routes(
    app: Any,
    rt: Any,
    form_template_service: "FormTemplateService",
    user_service: Any = None,
    **_kwargs: Any,
) -> list[Any]:
    """Create form template lesson-linking routes (admin-only).

    CRUD routes are registered by CRUDRouteFactory before this function is called.
    This function only handles domain-specific lesson linking.
    """

    get_user_service = make_service_getter(user_service)

    # ========================================================================
    # LESSON LINKING
    # ========================================================================

    @rt("/api/form-templates/link-lesson", methods=["POST"])
    @require_admin(get_user_service)
    @boundary_handler()
    async def link_form_to_lesson(request: Request, current_user: Any = None) -> Result[Any]:
        """Link a FormTemplate to a Lesson via EMBEDS_FORM."""
        parsed = await parse_json_body(request, FormLessonLinkRequest)
        if parsed.is_error:
            return parsed  # type: ignore[return-value]
        req = parsed.value

        return await form_template_service.link_to_lesson(req.form_template_uid, req.lesson_uid)

    @rt("/api/form-templates/unlink-lesson", methods=["POST"])
    @require_admin(get_user_service)
    @boundary_handler()
    async def unlink_form_from_lesson(request: Request, current_user: Any = None) -> Result[Any]:
        """Remove EMBEDS_FORM link between FormTemplate and Lesson."""
        parsed = await parse_json_body(request, FormLessonLinkRequest)
        if parsed.is_error:
            return parsed  # type: ignore[return-value]
        req = parsed.value

        return await form_template_service.unlink_from_lesson(req.form_template_uid, req.lesson_uid)

    return []
