"""
Groups API Routes — Domain-Specific Only
==========================================

Membership and student-facing routes for groups.
CRUD routes are handled by CRUDRouteFactory (see groups_routes.py).

See: /docs/decisions/ADR-040-teacher-exercise-workflow.md
"""

from typing import TYPE_CHECKING, Any

from fasthtml.common import Request

from adapters.inbound.auth import require_authenticated_user
from adapters.inbound.auth.roles import UserRole, make_service_getter, require_role
from adapters.inbound.boundary import boundary_handler
from adapters.inbound.csrf import csrf_protected
from adapters.inbound.form_helpers import parse_json_body
from adapters.inbound.route_factories import verify_entity_ownership
from core.models.group.group import Group
from core.models.group.group_request import GroupMemberRequest
from core.utils.logging import get_logger
from core.utils.result_simplified import Result

if TYPE_CHECKING:
    from core.ports import GroupOperations

logger = get_logger(__name__)


def create_groups_api_routes(
    app: Any,
    rt: Any,
    group_service: "GroupOperations",
    user_service: Any,
) -> list[Any]:
    """
    Create group domain-specific API routes (membership + student-facing).

    CRUD routes are auto-generated by CRUDRouteFactory.
    """

    get_user_service = make_service_getter(user_service)

    # ========================================================================
    # STUDENT-FACING
    # ========================================================================

    @rt("/api/groups/mine", methods=["GET"])
    @boundary_handler()
    async def my_groups(request: Request) -> Result[list[Group]]:
        """List groups the current user is a member of."""
        user_uid = require_authenticated_user(request)
        return await group_service.get_user_groups(user_uid)

    # ========================================================================
    # MEMBERSHIP ROUTES (Owner-only for add/remove)
    # ========================================================================

    @rt("/api/groups/{uid}/members/add", methods=["POST"])
    @csrf_protected
    @require_role(UserRole.TEACHER, get_user_service)
    @boundary_handler()
    async def add_member(request: Request, uid: str, current_user: Any = None) -> Result[bool]:
        """Add a member to a group. Owner only."""
        ownership_error = await verify_entity_ownership(
            group_service, uid, current_user.uid, "group"
        )
        if ownership_error:
            return ownership_error

        result = await parse_json_body(request, GroupMemberRequest)
        if result.is_error:
            return Result.fail(result)
        req = result.value

        return await group_service.add_member(
            group_uid=uid,
            user_uid=req.user_uid,
            role=req.role,
        )

    @rt("/api/groups/{uid}/members/remove", methods=["POST"])
    @csrf_protected
    @require_role(UserRole.TEACHER, get_user_service)
    @boundary_handler()
    async def remove_member(request: Request, uid: str, current_user: Any = None) -> Result[bool]:
        """Remove a member from a group. Owner only."""
        ownership_error = await verify_entity_ownership(
            group_service, uid, current_user.uid, "group"
        )
        if ownership_error:
            return ownership_error

        result = await parse_json_body(request, GroupMemberRequest)
        if result.is_error:
            return Result.fail(result)
        req = result.value

        return await group_service.remove_member(
            group_uid=uid,
            user_uid=req.user_uid,
        )

    @rt("/api/groups/{uid}/members", methods=["GET"])
    @boundary_handler()
    async def list_members(request: Request, uid: str) -> Result[list[dict[str, Any]]]:
        """List group members. Accessible to owner and members."""
        user_uid = require_authenticated_user(request)

        # Membership roster is classroom data — gate on the same owner-OR-member
        # predicate the group detail read uses. Non-members get the not_found
        # that a nonexistent group returns, so the roster cannot be enumerated.
        access = await group_service.get_for_user(uid, user_uid)
        if access.is_error:
            return Result.fail(access)

        return await group_service.get_members(uid)

    logger.info("Groups API routes registered (domain-specific only, CRUD via factory)")
    return []
