"""
PathStep Task Template Routes — Configuration-Driven Registration
==================================================================

Wires CRUD + PS-attachment endpoints for TaskTemplate (Phase 5).

CRUD (create/get/update/delete/list) is generated by CRUDRouteFactory via
CRUDRouteConfig. PS-attachment endpoints (attach/detach/list-by-ps) are
registered by the shared api_factory in
``_pathstep_template_routes_helpers.py``.
"""

from typing import TYPE_CHECKING, Any

from adapters.inbound._pathstep_template_routes_helpers import (
    make_pathstep_template_route_config,
)
from adapters.inbound.fasthtml_types import FastHTMLApp, RouteDecorator
from adapters.inbound.route_factories import register_domain_routes
from core.models.templates.task_template_request import (
    TaskTemplateCreateRequest,
    TaskTemplateUpdateRequest,
)

if TYPE_CHECKING:
    from services_bootstrap import Services


PATHSTEP_TASK_TEMPLATES_CONFIG = make_pathstep_template_route_config(
    domain_name="pathstep-task-templates",
    primary_service_attr="task_templates",
    create_schema=TaskTemplateCreateRequest,
    update_schema=TaskTemplateUpdateRequest,
    uid_prefix="tt",
)


def create_pathstep_task_templates_routes(
    app: FastHTMLApp,
    rt: RouteDecorator,
    services: "Services | None",
    _sync_service: Any = None,
) -> None:
    """Wire TaskTemplate CRUD + PS-attachment routes."""
    register_domain_routes(app, rt, services, PATHSTEP_TASK_TEMPLATES_CONFIG)


__all__ = ["create_pathstep_task_templates_routes"]
