"""
Principles API - Analytics and Domain-Specific Routes
=======================================================

CRUD, Query, and Intelligence factories are now registered via config in
principles_routes.py.  This file contains only factories and routes that require
runtime closures or domain-specific handler logic:
- AnalyticsRouteFactory (custom async handler)
- Manual domain routes (expressions, alignment, links, search)
"""

from typing import Any

from fasthtml.common import Request

from adapters.inbound.auth import require_authenticated_user, require_ownership_query
from adapters.inbound.boundary import boundary_handler
from adapters.inbound.route_factories.analytics_route_factory import AnalyticsRouteFactory
from core.models.ku.ku_request import (
    AlignmentAssessmentRequest,
    PrincipleExpressionRequest,
    PrincipleLinkRequest,
)
from core.ports.facade_protocols import PrinciplesFacadeProtocol
from core.services.conversion_service import ConversionService
from core.utils.result_simplified import Result
from core.utils.uid_generator import UIDGenerator

conversion_service = ConversionService()


def create_principles_api_routes(
    app: Any,
    rt: Any,
    principles_service: PrinciplesFacadeProtocol,
    **_kwargs: Any,
) -> list[Any]:
    """
    Create principles API routes that require runtime closures or domain-specific logic.

    CRUD, Query, and Intelligence routes are registered by register_domain_routes
    before this function is called (see principles_routes.py → PRINCIPLES_CONFIG).

    Args:
        app: FastHTML application instance
        rt: Route decorator
        principles_service: PrinciplesService instance (primary service)
        **_kwargs: Absorbs related services passed by register_domain_routes
    """

    # Service getter for ownership decorator (SKUEL012: named function, not lambda)
    def get_principles_service():
        return principles_service

    # ========================================================================
    # DOMAIN-SPECIFIC ROUTES (Manual)
    # ========================================================================
    # SECURITY: All UID-based routes verify user owns the principle before operating

    # NOTE: GET /api/principles/user/{user_uid} now generated by CommonQueryRouteFactory

    # Principle Expressions and Alignment
    # ------------------------------------

    @rt("/api/principles/expressions", methods=["POST"])
    @require_ownership_query(get_principles_service, uid_param="principle_uid")
    @boundary_handler(success_status=201)
    async def create_principle_expression_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """Create a principle expression (requires ownership)."""
        body = await request.json()
        data = PrincipleExpressionRequest.model_validate(body)

        expression_uid = UIDGenerator.generate_uid("expression", data.context[:50])
        dto = conversion_service.principle_expression_to_dto(expression_uid, entity.uid, data)

        return await principles_service.create_principle_expression(dto)

    @rt("/api/principles/expressions")
    @require_ownership_query(get_principles_service, uid_param="principle_uid")
    @boundary_handler()
    async def get_principle_expressions_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """Get all expressions for a principle (requires ownership)."""
        return await principles_service.get_principle_expressions(entity.uid)

    @rt("/api/principles/alignment", methods=["POST"])
    @require_ownership_query(get_principles_service, uid_param="principle_uid")
    @boundary_handler()
    async def assess_principle_alignment_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """
        Assess alignment with a principle (requires ownership).

        Implements SKUEL's dual-track philosophy:
        - Stores user's self-assessment (what they believe)
        - Calculates system alignment (what they do)
        - Returns gap analysis (perception vs reality)

        Returns PrincipleAlignmentAssessmentResult containing both tracks.
        """
        body = await request.json()
        data = AlignmentAssessmentRequest.model_validate(body)

        # Extract min_confidence from request if provided, otherwise use default
        min_confidence = getattr(data, "min_confidence", 0.7)

        # Use hybrid dual-track assessment: store user input AND calculate system alignment
        result: Result[Any] = await principles_service.alignment.assess_with_user_input(
            principle_uid=entity.uid,
            user_uid=user_uid,
            user_alignment_level=data.alignment_level,
            user_evidence=data.evidence,
            user_reflection=data.reflection,
            min_confidence=min_confidence,
        )
        return result

    @rt("/api/principles/alignment-history")
    @require_ownership_query(get_principles_service, uid_param="principle_uid")
    @boundary_handler()
    async def get_principle_alignment_history_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """Get alignment history for a principle (requires ownership)."""
        params = dict(request.query_params)
        limit = int(params.get("limit", 20))
        days = int(params.get("days", 30))

        return await principles_service.get_principle_alignment_history(entity.uid, limit, days)

    # Principle Relationships and Linking
    # ------------------------------------
    # SECURITY: All routes verify user owns the principle before operating

    @rt("/api/principles/links", methods=["POST"])
    @require_ownership_query(get_principles_service, uid_param="principle_uid")
    @boundary_handler(success_status=201)
    async def create_principle_link_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """Create a link between principles (requires ownership)."""
        body = await request.json()
        data = PrincipleLinkRequest.model_validate(body)

        link_uid = UIDGenerator.generate_uid("link", f"{entity.uid}-{data.uid}")
        dto = conversion_service.principle_link_to_dto(link_uid, entity.uid, data)

        return await principles_service.create_principle_link(dto)

    @rt("/api/principles/links")
    @require_ownership_query(get_principles_service, uid_param="principle_uid")
    @boundary_handler()
    async def get_principle_links_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """Get all links for a principle (requires ownership)."""
        params = dict(request.query_params)
        link_type = params.get("type")

        return await principles_service.get_principle_links(entity.uid, link_type)

    @rt("/api/principles/related")
    @require_ownership_query(get_principles_service, uid_param="principle_uid")
    @boundary_handler()
    async def get_related_principles_route(
        request: Request, user_uid: str, entity: Any
    ) -> Result[Any]:
        """Get related principles based on connections (requires ownership)."""
        params = dict(request.query_params)
        depth = int(params.get("depth", 2))
        limit = int(params.get("limit", 10))

        return await principles_service.get_related_principles(entity.uid, depth, limit)

    # Principle Search and Discovery
    # -------------------------------

    @rt("/api/principles/search")
    @boundary_handler()
    async def search_principles_route(request: Request) -> Result[Any]:
        """Search principles by content and metadata."""
        body = await request.json()
        query = body.get("query", "")
        filters = body.get("filters", {})
        limit = body.get("limit", 20)

        return await principles_service.search_principles(query, filters, limit)

    @rt("/api/principles/categories")
    @boundary_handler()
    async def get_principle_categories_route(request: Request) -> Result[Any]:
        """Get principle categories for the authenticated user."""
        user_uid = require_authenticated_user(request)
        return await principles_service.get_principle_categories(user_uid)

    @rt("/api/principles/sources")
    @boundary_handler()
    async def get_principle_sources_route(_request: Request) -> Result[Any]:
        """Get all principle sources with counts."""
        return await principles_service.get_principle_sources()

    # ========================================================================
    # ANALYTICS ROUTES (Factory-Generated)
    # ========================================================================

    # Analytics handler functions
    async def handle_principles_stats(service, params):
        """Handle principles statistics and summary."""
        user_uid = params.get("user_uid", "current_user")
        return await service.get_principles_stats(user_uid)

    # Create analytics factory
    analytics_factory = AnalyticsRouteFactory(
        service=principles_service,
        domain_name="principles",
        analytics_config={
            "stats": {
                "path": "/api/principles/stats",
                "handler": handle_principles_stats,
                "description": "Get principles statistics and summary",
                "methods": ["GET"],
            }
        },
    )
    analytics_factory.register_routes(app, rt)

    return []  # Routes registered via @rt() decorators (no objects returned)
