"""
Knowledge Service - Facade
===========================

Unified interface for all knowledge operations.
Delegates to specialized sub-services for focused responsibilities.

**Backward Compatibility:** This facade maintains the exact same API as the
original monolithic service. External code requires zero changes.

Version: 5.0 (Consolidated Architecture - January 2026 ADR-031)
Date: 2026-01-11

Architecture (v5.0 - KU Consolidation):
---------------------------------------
Consolidated from 7 sub-services to 6:
- KuCoreService: CRUD operations
- KuSearchService: Search and discovery
- KuGraphService: Graph navigation and relationships
- KuSemanticService: Semantic relationship management
- KuPracticeService: Event-driven practice tracking
- KuInteractionService: Pedagogical tracking (VIEWED->IN_PROGRESS->MASTERED)

DELETED (January 2026):
- KuLpService: Redundant delegation to LpService (use LpService directly)

Note: Graph and Semantic services are internal implementation details.
External callers should use the KuService facade methods.
"""

from datetime import datetime
from typing import TYPE_CHECKING, Any

from core.constants import GraphDepth, QueryLimit
from core.services.mixins import FacadeDelegationMixin, merge_delegations

if TYPE_CHECKING:
    from neo4j import AsyncDriver

    from core.services.protocols import (
        EventBusOperations,
        KuOperations,
        QueryBuilderOperations,
    )
    from core.services.user import UserContext

# Import models for type hints
# SemanticRelationshipType needed at runtime for enum conversion
from core.infrastructure.relationships.semantic_relationships import SemanticRelationshipType
from core.models.ku.ku_dto import KuDTO

# Import sub-services
from core.services.ku.ku_ai_service import KuAIService
from core.services.protocols.base_protocols import HasUID
from core.utils.decorators import with_error_handling
from core.utils.error_boundary import safe_event_handler
from core.utils.logging import get_logger
from core.utils.metrics import get_metrics_summary
from core.utils.result_simplified import Errors, Result
from core.utils.sort_functions import get_second_item


class KuService(FacadeDelegationMixin):
    """
    Unified facade for knowledge operations.

    Delegates to specialized sub-services (January 2026 - ADR-031):
    - KuCoreService: CRUD operations
    - KuSearchService: Search and discovery
    - KuGraphService: Graph navigation and relationships
    - KuSemanticService: Semantic relationship management
    - KuPracticeService: Event-driven practice tracking
    - KuInteractionService: Pedagogical tracking
    - UnifiedRelationshipService: Harmonious relationship operations
    - KuIntelligenceService: Intelligence and analytics

    Access relationship operations via self.relationships:
    - get_related_entities("prerequisites", uid) - Get prerequisite KUs
    - get_related_entities("enables_learning", uid) - Get enabled KUs
    - get_related_entities("applied_in_tasks", uid) - Get tasks that apply this KU
    - get_related_entities("reinforced_by_habits", uid) - Get habits that reinforce this KU

    Source Tag: "ku_service_explicit"
    - Format: "ku_service_explicit" for user-created relationships
    - Format: "ku_service_inferred" for system-generated relationships

    Confidence Scoring:
    - 0.9+: User explicitly defined relationship
    - 0.7-0.9: Inferred from ku metadata
    - 0.5-0.7: Suggested based on patterns
    - <0.5: Low confidence, needs verification

    Auto-Generated Delegations (via FacadeDelegationMixin):
    - Core: create, get, update, delete, publish, archive, get_user_mastery, get_chunks, analyze_content
    - Search: search_by_title_template, search_with_user_context, find_similar_content, etc.
    - Graph: find_prerequisites, find_next_steps, get_knowledge_with_context, etc.
    - Semantic: create_with_semantic_relationships, get_semantic_neighborhood

    Explicit Methods (custom logic):
    - get_knowledge_units_batch, list_user_knowledge, get_enables
    - Tag/content management: add_knowledge_tags, remove_knowledge_tags, update_ku_content
    - Event handlers: handle_knowledge_*, increment_substance_metric
    - API methods: find_related_knowledge, get_knowledge_recommendations, etc.

    Note: Learning path operations should use LpService directly (ADR-031).

    SKUEL Architecture:
    - Uses FacadeDelegationMixin for ~30 auto-generated delegation methods
    - Uses CypherGenerator for ALL graph queries
    - No APOC calls (Phase 5 eliminated those)
    - Returns Result[T] for error handling
    - Logs operations with structured logging

    """

    # ========================================================================
    # TYPE STUBS FOR DELEGATED METHODS (MyPy visibility)
    # ========================================================================
    # These stubs tell MyPy about dynamically generated delegation methods.
    # Actual implementation is generated by FacadeDelegationMixin at class definition.
    if TYPE_CHECKING:
        from core.models.ku.ku import Ku

        async def get(self, uid: str) -> Result[Ku | None]: ...
        async def create(self, data: dict[str, Any]) -> Result[Ku]: ...
        async def update(self, uid: str, updates: dict[str, Any]) -> Result[Ku]: ...
        async def delete(self, uid: str) -> Result[bool]: ...

    # ========================================================================
    # DELEGATION SPECIFICATION (FacadeDelegationMixin)
    # ========================================================================
    _delegations = merge_delegations(
        # Core CRUD delegations
        {
            "create": ("core", "create"),
            "get": ("core", "get"),
            "update": ("core", "update"),
            "delete": ("core", "delete"),
            "publish": ("core", "publish"),
            "archive": ("core", "archive"),
            "get_user_mastery": ("core", "get_user_mastery"),
            "get_chunks": ("core", "get_chunks"),
            "analyze_content": ("core", "analyze_content"),
            "get_with_template": ("core", "get"),
        },
        # Search delegations (using search_service, not search to match sub-service name)
        {
            "search_by_title_template": ("search_service", "search_by_title_template"),
            "search_with_user_context": ("search_service", "search_with_user_context"),
            "find_similar_content": ("search_service", "find_similar_content"),
            "search_by_tags": ("search_service", "search_by_tags"),
            "search_by_facets": ("search_service", "search_by_facets"),
            "search_chunks_with_facets": ("search_service", "search_chunks_with_facets"),
            "search_chunks": ("search_service", "search_chunks"),
            "search_by_features": ("search_service", "search_by_features"),
            "search_with_semantic_intent": ("search_service", "search_with_semantic_intent"),
            "get_content_chunks": ("search_service", "get_content_chunks"),
        },
        # Graph delegations
        {
            "find_prerequisites": ("graph", "find_prerequisites"),
            "find_next_steps": ("graph", "find_next_steps"),
            "get_knowledge_with_context": ("graph", "get_knowledge_with_context"),
            "link_prerequisite": ("graph", "link_prerequisite"),
            "link_parent_child": ("graph", "link_parent_child"),
            "get_prerequisite_chain": ("graph", "get_prerequisite_chain"),
            "analyze_knowledge_gaps": ("graph", "analyze_knowledge_gaps"),
            "get_learning_recommendations": ("graph", "get_learning_recommendations"),
            "find_time_aware_learning_path": ("graph", "find_time_aware_learning_path"),
            "update_hub_scores": ("graph", "update_hub_scores"),
            "get_foundational_knowledge": ("graph", "get_foundational_knowledge"),
            # Application discovery (reverse relationship queries)
            "find_events_applying_knowledge": ("graph", "find_events_applying_knowledge"),
            "find_habits_reinforcing_knowledge": ("graph", "find_habits_reinforcing_knowledge"),
            # Reverse lookups - curriculum (Phase 2)
            "find_learning_steps_containing": ("graph", "find_learning_steps_containing"),
            "find_learning_paths_teaching": ("graph", "find_learning_paths_teaching"),
            # Reverse lookups - activity domains (Phase 2)
            "find_tasks_applying_knowledge": ("graph", "find_tasks_applying_knowledge"),
            "find_goals_requiring_knowledge": ("graph", "find_goals_requiring_knowledge"),
            "find_choices_informed_by_knowledge": ("graph", "find_choices_informed_by_knowledge"),
            "find_principles_embodying_knowledge": ("graph", "find_principles_embodying_knowledge"),
        },
        # Semantic delegations
        {
            "create_with_semantic_relationships": (
                "semantic",
                "create_with_semantic_relationships",
            ),
            "get_semantic_neighborhood": ("semantic", "get_semantic_neighborhood"),
        },
        # Adaptive curriculum delegations
        {
            "get_personalized_curriculum": ("adaptive", "get_personalized_curriculum"),
            "get_sel_journey": ("adaptive", "get_sel_journey"),
            "track_curriculum_completion": ("adaptive", "track_curriculum_completion"),
        },
    )

    def __init__(
        self,
        repo: "KuOperations",
        content_repo: "Any | None" = None,  # Was ContentOperations (deleted January 2026)
        neo4j_adapter: "Any | None" = None,
        chunking_service: "Any | None" = None,
        graph_intelligence_service: "Any | None" = None,
        query_builder: "QueryBuilderOperations | None" = None,
        event_bus: "EventBusOperations | None" = None,
        driver: "AsyncDriver | None" = None,
        user_service: "Any | None" = None,
        ai_service: KuAIService | None = None,
        vector_search_service: "Any | None" = None,
        embeddings_service: "Any | None" = None,
    ) -> None:
        """
        Initialize facade with all dependencies via factory.

        FAIL-FAST ARCHITECTURE (per CLAUDE.md):
        The repo (backend) and graph_intelligence_service are REQUIRED.
        Services run at full capacity or fail immediately at startup.

        **January 2026 - Factory Pattern (Architecture Consistency Review):**
        Uses create_ku_sub_services() factory for consistent initialization.
        Factory handles circular dependency: intelligence created before core.

        Args:
            repo: KuOperations backend - REQUIRED
            content_repo: Content storage backend (optional)
            neo4j_adapter: Neo4j adapter for graph operations (optional)
            chunking_service: Chunking service for RAG (optional)
            graph_intelligence_service: GraphIntelligenceService - REQUIRED for cross-domain queries
            query_builder: QueryBuilder service for optimized queries (optional)
            event_bus: Event bus for publishing domain events (optional)
            driver: Neo4j async driver for Phase 4 event-driven operations (optional)
            user_service: UserService for UserContext access (January 2026 - KU-Activity Integration)
            ai_service: Optional KuAIService for AI features (ADR-030 separation)
            vector_search_service: Optional Neo4jVectorSearchService for semantic search (January 2026 - GenAI)
            embeddings_service: Optional Neo4jGenAIEmbeddingsService for embedding generation (January 2026 - GenAI)
        """
        # FAIL-FAST: Backend is REQUIRED
        if not repo:
            raise ValueError(
                "KuService backend (repo) is REQUIRED. "
                "SKUEL follows fail-fast architecture - all required dependencies "
                "must be provided at initialization."
            )
        if not graph_intelligence_service:
            raise ValueError(
                "KuService graph_intelligence_service is REQUIRED. "
                "SKUEL follows fail-fast architecture - graph intelligence enables "
                "cross-domain queries for curriculum domains."
            )

        # Create all sub-services via factory (January 2026 - Architecture Consistency)
        from core.utils.curriculum_domain_config import create_ku_sub_services

        subs = create_ku_sub_services(
            backend=repo,
            content_repo=content_repo,
            neo4j_adapter=neo4j_adapter,
            chunking_service=chunking_service,
            graph_intelligence_service=graph_intelligence_service,
            query_builder=query_builder,
            event_bus=event_bus,
            driver=driver,
            user_service=user_service,
            vector_search_service=vector_search_service,  # NEW: January 2026 GenAI
            embeddings_service=embeddings_service,  # NEW: January 2026 GenAI
        )

        # Assign sub-services from factory result
        self.core = subs.core
        self.search_service = subs.search
        self.graph = subs.graph
        self.semantic = subs.semantic
        self.practice = subs.practice
        self.interaction = subs.interaction
        self.relationships = subs.relationships
        self.intelligence = subs.intelligence
        self.adaptive = subs.adaptive

        # Expose search attribute for convenience (test compatibility)
        # Note: We use search_service internally to avoid shadowing
        self.search = self.search_service

        # Store dependencies for backward compatibility
        self.repo = repo
        self.content_repo = content_repo
        self.chunking_service = chunking_service
        self.graph_intel = graph_intelligence_service
        self.neo4j_adapter = neo4j_adapter
        self.user_service = user_service

        # Optional AI service (ADR-030: AI features are optional)
        self.ai: KuAIService | None = ai_service

        self.logger = get_logger("skuel.services.ku")
        self.logger.debug(
            "KuService initialized via factory (8 sub-services, circular dependency handled)"
        )

    # ========================================================================
    # CORE CRUD OPERATIONS - Delegated to KuCoreService
    # ========================================================================
    # Note: Simple delegations (create, get, update, delete, publish, archive,
    # get_user_mastery, get_chunks, analyze_content) auto-generated by FacadeDelegationMixin.

    async def get_knowledge_units_batch(self, uids: list[str]) -> Result[list[Any]]:
        """
        Get multiple knowledge units in one batched query.

        Critical for GraphQL DataLoader batching to prevent N+1 queries.

        Args:
            uids: List of knowledge unit UIDs to fetch

        Returns:
            Result containing list of KuDTOs (None for missing UIDs)
            Entities returned in same order as input UIDs
        """
        if not self.repo:
            return Result.fail(
                Errors.system(
                    "Knowledge repository not available", operation="get_knowledge_units_batch"
                )
            )

        # Use UniversalNeo4jBackend's get_many() method
        return await self.repo.get_many(uids)

    async def list_user_knowledge(self, user_uid: str) -> Result[list]:
        """
        Get all knowledge units available for user's semantic search.

        This method supports Askesis RAG semantic search by returning all knowledge
        units that can be queried. Currently returns ALL knowledge units (global
        knowledge base approach), as Knowledge Units in SKUEL are not user-scoped.

        Future Enhancement: Could scope to user's learning path via:
            MATCH (user:User {uid: $user_uid})-[:LEARNING]->(ku:Ku)

        Args:
            user_uid: User identifier (currently unused, reserved for future scoping)

        Returns:
            Result containing list of Ku domain models

        Implementation Notes:
            - Knowledge Units are global content, not user-specific
            - User scoping happens via LEARNING relationships, not ownership
            - Returns domain models (Ku), not DTOs
            - Used by askesis_service._find_similar_knowledge() for semantic search

        Performance:
            - Fetches up to 10,000 knowledge units (high limit for global access)
            - Results are NOT cached (semantic search caches embeddings instead)
            - Consider adding pagination if knowledge base exceeds 10k units
        """
        if not self.repo:
            return Result.fail(
                Errors.system("Knowledge repository not available", operation="list_user_knowledge")
            )

        # Get all knowledge units from backend (global knowledge base)
        # High limit since knowledge is global, not user-scoped
        result = await self.repo.list(QueryLimit.BULK)

        if result.is_error:
            self.logger.error(f"Failed to list knowledge units: {result.error}")
            return Result.fail(result.expect_error())

        # Unpack tuple: backend.list() returns (kus, total_count)
        kus_data, _ = result.value

        # Backend returns Ku instances (entity_class=Ku), not KuDTOs
        kus = list(kus_data)

        self.logger.info(
            f"Retrieved {len(kus)} knowledge units for semantic search (user: {user_uid})"
        )

        return Result.ok(kus)

    # ========================================================================
    # SEARCH OPERATIONS - Delegated to KuSearchService
    # ========================================================================
    # Note: Simple delegations (search_by_title_template, search_with_user_context,
    # find_similar_content, search_by_tags, search_by_facets, search_chunks_with_facets,
    # search_chunks, search_by_features, search_with_semantic_intent, get_content_chunks)
    # auto-generated by FacadeDelegationMixin.

    # ========================================================================
    # GRAPH OPERATIONS - Delegated to KuGraphService
    # ========================================================================
    # Note: Simple delegations (find_prerequisites, find_next_steps, get_knowledge_with_context,
    # link_prerequisite, link_parent_child, get_prerequisite_chain, analyze_knowledge_gaps,
    # get_learning_recommendations, find_time_aware_learning_path, update_hub_scores,
    # get_foundational_knowledge) auto-generated by FacadeDelegationMixin.

    async def get_prerequisites(self, uid: str) -> Result[list[KuDTO]]:
        """
        Get prerequisite knowledge units (GraphQL-friendly alias).

        Wrapper for find_prerequisites() with sensible defaults for GraphQL resolvers.
        Returns Result[list[KuDTO]].
        """
        return await self.graph.find_prerequisites(uid=uid, depth=GraphDepth.DEFAULT)

    async def get_enables(self, uid: str) -> Result[list[KuDTO]]:
        """
        Get knowledge units enabled by this KU (GraphQL-friendly method).

        Returns Result[list[KuDTO]] - knowledge units that become accessible
        after mastering this one.

        Implementation: Uses graph.find_next_steps (KUs that require this one).
        """
        # find_next_steps returns KUs that have this KU as a prerequisite
        # which is semantically the same as what this KU enables
        return await self.graph.find_next_steps(uid=uid)

    # ========================================================================
    # SEMANTIC OPERATIONS - Delegated to KuSemanticService
    # ========================================================================
    # Note: Simple delegations (create_with_semantic_relationships, get_semantic_neighborhood)
    # auto-generated by FacadeDelegationMixin.

    async def create_knowledge_relationship(
        self,
        source_uid: str,
        target_uid: str,
        relationship_type: "SemanticRelationshipType",
        confidence: float = 0.9,
        strength: float = 1.0,
        notes: str | None = None,
    ) -> Result[bool]:
        """
        Create a semantic relationship between two knowledge units.

        Args:
            source_uid: Source knowledge unit UID (subject)
            target_uid: Target knowledge unit UID (object)
            relationship_type: SemanticRelationshipType enum value
            confidence: Confidence score (0.0-1.0)
            strength: Strength of relationship (0.0-1.0)
            notes: Optional notes about the relationship

        Returns:
            Result indicating success
        """
        return await self.semantic.add_semantic_relationship(
            subject_uid=source_uid,
            predicate=relationship_type,
            object_uid=target_uid,
            confidence=confidence,
            strength=strength,
            notes=notes,
        )

    async def get_knowledge_relationships(
        self, uid: str, relationship_type: str | None = None
    ) -> Result[list[dict[str, Any]]]:
        """
        Get relationships for a knowledge unit.

        Args:
            uid: Knowledge unit UID
            relationship_type: Filter by relationship type (e.g., "learn:requires_theoretical_understanding")

        Returns:
            Result with list of relationships
        """
        if not relationship_type:
            return Result.fail(
                Errors.validation(
                    message="relationship_type is required (e.g., 'learn:requires_theoretical_understanding')",
                    field="relationship_type",
                )
            )

        # Convert string to SemanticRelationshipType enum
        try:
            predicate = SemanticRelationshipType(relationship_type)
        except ValueError:
            return Result.fail(
                Errors.validation(
                    message=f"Invalid relationship_type: {relationship_type}",
                    field="relationship_type",
                )
            )

        return await self.semantic.get_relationships_by_type(uid=uid, predicate=predicate)

    async def get_knowledge_dependencies(self, uid: str, limit: int = 10) -> Result[list[KuDTO]]:
        """
        Get knowledge units that depend on this one.

        Args:
            uid: Knowledge unit UID
            limit: Maximum results to return

        Returns:
            Result with list of dependent knowledge units
        """
        return await self.graph.find_next_steps(uid=uid, limit=limit)

    # ========================================================================
    # CONTENT AND TAG MANAGEMENT
    # ========================================================================

    async def update_ku_content(
        self, uid: str, content: str, title: str | None = None
    ) -> Result[KuDTO]:
        """
        Update a knowledge unit's content.

        Args:
            uid: Knowledge unit UID
            content: New content text
            title: Optional new title

        Returns:
            Result with updated knowledge unit
        """
        updates: dict[str, Any] = {"content": content}
        if title:
            updates["title"] = title
        return await self.core.update(uid, updates)

    async def add_knowledge_tags(self, uid: str, tags: list[str]) -> Result[KuDTO]:
        """
        Add tags to a knowledge unit.

        Args:
            uid: Knowledge unit UID
            tags: Tags to add

        Returns:
            Result with updated knowledge unit
        """
        # First get current tags
        ku_result = await self.core.get(uid)
        if ku_result.is_error:
            return Result.fail(ku_result.expect_error())

        ku = ku_result.value
        if not ku:
            return Result.fail(Errors.not_found(resource="Ku", identifier=uid))

        current_tags = list(ku.tags or [])
        # Add new tags without duplicates
        updated_tags = list(set(current_tags + tags))

        return await self.core.update(uid, {"tags": updated_tags})

    async def remove_knowledge_tags(self, uid: str, tags: list[str]) -> Result[KuDTO]:
        """
        Remove tags from a knowledge unit.

        Args:
            uid: Knowledge unit UID
            tags: Tags to remove

        Returns:
            Result with updated knowledge unit
        """
        # First get current tags
        ku_result = await self.core.get(uid)
        if ku_result.is_error:
            return Result.fail(ku_result.expect_error())

        ku = ku_result.value
        if not ku:
            return Result.fail(Errors.not_found(resource="Ku", identifier=uid))

        current_tags = list(ku.tags or [])
        # Remove specified tags
        updated_tags = [t for t in current_tags if t not in tags]

        return await self.core.update(uid, {"tags": updated_tags})

    # ========================================================================
    # SEARCH AND FILTERING
    # ========================================================================

    async def search_knowledge_units(self, query: str, limit: int = 50) -> Result[list[KuDTO]]:
        """
        Search knowledge units by text query.

        Args:
            query: Search query string
            limit: Maximum results to return

        Returns:
            Result with list of matching knowledge units
        """
        return await self.search_service.search_by_title_template(query=query, limit=limit)

    async def get_knowledge_by_domain(self, domain: str, limit: int = 100) -> Result[list[Any]]:
        """
        Get knowledge units by domain.

        Args:
            domain: Domain name (e.g., "TECH", "BUSINESS")
            limit: Maximum results

        Returns:
            Result with list of knowledge units in the domain
        """
        if not self.repo:
            return Result.fail(
                Errors.system(
                    message="Knowledge repository not available",
                    operation="get_knowledge_by_domain",
                )
            )

        # Use backend's find_by with domain filter
        return await self.repo.find_by(domain=domain, limit=limit)

    # ========================================================================
    # TEMPLATE & UTILITY OPERATIONS
    # ========================================================================
    # Note: get_with_template auto-generated by FacadeDelegationMixin (maps to core.get).

    @with_error_handling("get_query_metrics", error_type="system")
    async def get_query_metrics(self) -> Result[dict[str, Any]]:
        """
        Get query performance metrics for all knowledge operations.

        Returns comprehensive metrics including:
        - Per-operation call counts and timings
        - Statistical distribution (min, max, avg, p95, p99)
        - Error rates and counts
        - Overall system statistics

        Returns:
            Result containing dictionary with:
            - uptime_seconds: Time since metrics started
            - total_operations: Number of unique operations tracked
            - total_calls: Total calls across all operations
            - total_errors: Total errors across all operations
            - overall_error_rate: Percentage of calls that errored
            - calls_per_second: Request throughput
            - slowest_operations: Top 5 slowest operations
            - operations: Detailed per-operation metrics
        """
        metrics = get_metrics_summary()
        return Result.ok(metrics)

    # Note: get_content_chunks auto-generated by FacadeDelegationMixin.

    # ========================================================================
    # SUBSTANCE TRACKING EVENT LISTENERS (October 17, 2025)
    # "Applied knowledge, not pure theory" - Track real-world application
    # ========================================================================

    @safe_event_handler("knowledge.applied_in_task")
    async def handle_knowledge_applied_in_task(self, event) -> None:
        """
        Handle KnowledgeAppliedInTask event.

        Increments: times_applied_in_tasks
        Updates: last_applied_date
        Invalidates: substance cache

        Args:
            event: KnowledgeAppliedInTask with knowledge_uid, task_uid, occurred_at
        """
        await self.increment_substance_metric(
            ku_uid=event.knowledge_uid,
            metric="times_applied_in_tasks",
            timestamp_field="last_applied_date",
            timestamp=event.occurred_at,
        )
        self.logger.debug(
            f"Substance updated: {event.knowledge_uid} applied in task {event.task_uid}"
        )

    @safe_event_handler("knowledge.practiced_in_event")
    async def handle_knowledge_practiced_in_event(self, event) -> None:
        """
        Handle KnowledgePracticedInEvent event.

        Increments: times_practiced_in_events
        Updates: last_practiced_date
        Invalidates: substance cache

        Args:
            event: KnowledgePracticedInEvent with knowledge_uid, event_uid, occurred_at
        """
        await self.increment_substance_metric(
            ku_uid=event.knowledge_uid,
            metric="times_practiced_in_events",
            timestamp_field="last_practiced_date",
            timestamp=event.occurred_at,
        )
        self.logger.debug(
            f"Substance updated: {event.knowledge_uid} practiced in event {event.event_uid}"
        )

    @safe_event_handler("knowledge.built_into_habit")
    async def handle_knowledge_built_into_habit(self, event) -> None:
        """
        Handle KnowledgeBuiltIntoHabit event.

        Increments: times_built_into_habits
        Updates: last_built_into_habit_date
        Invalidates: substance cache

        HIGHEST IMPACT EVENT (0.10 weight) - lifestyle integration

        Args:
            event: KnowledgeBuiltIntoHabit with knowledge_uid, habit_uid, occurred_at
        """
        await self.increment_substance_metric(
            ku_uid=event.knowledge_uid,
            metric="times_built_into_habits",
            timestamp_field="last_built_into_habit_date",
            timestamp=event.occurred_at,
        )
        # High-impact event - log at info level
        self.logger.info(
            f"Knowledge {event.knowledge_uid} built into habit {event.habit_uid} "
            f"(substance +0.10, lifestyle integration)"
        )

    @safe_event_handler("knowledge.informed_choice")
    async def handle_knowledge_informed_choice(self, event) -> None:
        """
        Handle KnowledgeInformedChoice event.

        Increments: choices_informed_count
        Updates: last_choice_informed_date
        Invalidates: substance cache

        HIGH IMPACT EVENT (0.07 weight) - decision-making

        Args:
            event: KnowledgeInformedChoice with knowledge_uid, choice_uid, occurred_at
        """
        await self.increment_substance_metric(
            ku_uid=event.knowledge_uid,
            metric="choices_informed_count",
            timestamp_field="last_choice_informed_date",
            timestamp=event.occurred_at,
        )
        self.logger.info(
            f"Knowledge {event.knowledge_uid} informed choice {event.choice_uid} "
            f"(substance +0.07, informed decision-making)"
        )

    # ========================================================================
    # BATCH KNOWLEDGE EVENT HANDLERS (Performance Optimization)
    # ========================================================================

    @safe_event_handler("knowledge.bulk_applied_in_task")
    async def handle_knowledge_bulk_applied_in_task(self, event) -> None:
        """
        Handle KnowledgeBulkAppliedInTask event - batch version.

        More efficient than N individual handle_knowledge_applied_in_task calls.

        Args:
            event: KnowledgeBulkAppliedInTask with knowledge_uids tuple
        """
        await self.batch_increment_substance_metric(
            ku_uids=event.knowledge_uids,
            metric="times_applied_in_tasks",
            timestamp_field="last_applied_date",
            timestamp=event.occurred_at,
        )
        self.logger.debug(
            f"Batch substance updated: {len(event.knowledge_uids)} KUs applied in task {event.task_uid}"
        )

    @safe_event_handler("knowledge.bulk_built_into_habit")
    async def handle_knowledge_bulk_built_into_habit(self, event) -> None:
        """
        Handle KnowledgeBulkBuiltIntoHabit event - batch version.

        HIGHEST IMPACT EVENT (0.10 weight per KU) - lifestyle integration.

        Args:
            event: KnowledgeBulkBuiltIntoHabit with knowledge_uids tuple
        """
        await self.batch_increment_substance_metric(
            ku_uids=event.knowledge_uids,
            metric="times_built_into_habits",
            timestamp_field="last_built_into_habit_date",
            timestamp=event.occurred_at,
        )
        self.logger.info(
            f"Batch: {len(event.knowledge_uids)} KUs built into habit {event.habit_uid} "
            f"(substance +0.10 each, lifestyle integration)"
        )

    @safe_event_handler("knowledge.bulk_informed_choice")
    async def handle_knowledge_bulk_informed_choice(self, event) -> None:
        """
        Handle KnowledgeBulkInformedChoice event - batch version.

        HIGH IMPACT EVENT (0.07 weight per KU) - decision-making.

        Args:
            event: KnowledgeBulkInformedChoice with knowledge_uids tuple
        """
        await self.batch_increment_substance_metric(
            ku_uids=event.knowledge_uids,
            metric="choices_informed_count",
            timestamp_field="last_choice_informed_date",
            timestamp=event.occurred_at,
        )
        self.logger.info(
            f"Batch: {len(event.knowledge_uids)} KUs informed choice {event.choice_uid} "
            f"(substance +0.07 each, informed decision-making)"
        )

    async def batch_increment_substance_metric(
        self, ku_uids: tuple[str, ...], metric: str, timestamp_field: str, timestamp
    ) -> None:
        """
        Atomically increment a substance metric for multiple KUs in one query.

        O(1) database round-trip vs O(n) for individual increments.

        Args:
            ku_uids: Tuple of knowledge unit UIDs
            metric: Field name to increment
            timestamp_field: Timestamp field to update
            timestamp: DateTime value for timestamp field

        Raises:
            Exception: Propagated to caller (typically @safe_event_handler decorator)
        """
        if not ku_uids:
            return

        timestamp_str = timestamp.isoformat() if isinstance(timestamp, datetime) else str(timestamp)

        # Batch atomic increment query using UNWIND
        query = f"""
        UNWIND $ku_uids AS ku_uid
        MATCH (ku:Ku {{uid: ku_uid}})
        SET ku.{metric} = COALESCE(ku.{metric}, 0) + 1,
            ku.{timestamp_field} = datetime($timestamp),
            ku._substance_cache_timestamp = NULL
        RETURN count(ku) as updated_count
        """

        params = {"ku_uids": list(ku_uids), "timestamp": timestamp_str}

        if self.neo4j_adapter:
            result = await self.neo4j_adapter.execute_query(query, params)
            if result and len(result) > 0:
                updated_count = result[0].get("updated_count", 0)
                self.logger.debug(f"Batch substance metric updated: {updated_count} KUs.{metric}")
        else:
            self.logger.warning(
                "Neo4j adapter not available - cannot batch increment substance metrics"
            )

    async def increment_substance_metric(
        self, ku_uid: str, metric: str, timestamp_field: str, timestamp
    ) -> None:
        """
        Atomically increment a substance metric in Neo4j.

        This is a CRITICAL operation - uses atomic Cypher SET to avoid race conditions.

        Args:
            ku_uid: Knowledge unit UID
            metric: Field name to increment (e.g., 'times_applied_in_tasks')
            timestamp_field: Timestamp field to update (e.g., 'last_applied_date')
            timestamp: DateTime value for timestamp field

        Behavior:
            - Increments count atomically
            - Updates timestamp
            - Invalidates substance cache (force recalculation)
            - Creates field if doesn't exist (COALESCE)

        Raises:
            Exception: Propagated to caller (typically @safe_event_handler decorator)
        """
        # Convert datetime to ISO string if needed
        timestamp_str = timestamp.isoformat() if isinstance(timestamp, datetime) else str(timestamp)

        # Atomic increment query
        query = f"""
        MATCH (ku:Ku {{uid: $ku_uid}})
        SET ku.{metric} = COALESCE(ku.{metric}, 0) + 1,
            ku.{timestamp_field} = datetime($timestamp),
            ku._substance_cache_timestamp = NULL
        RETURN ku.{metric} as new_count
        """

        params = {"ku_uid": ku_uid, "timestamp": timestamp_str}

        # Execute via neo4j_adapter if available
        if self.neo4j_adapter:
            result = await self.neo4j_adapter.execute_query(query, params)
            if result and len(result) > 0:
                new_count = result[0].get("new_count", 0)
                self.logger.debug(f"Substance metric updated: {ku_uid}.{metric} = {new_count}")
        else:
            self.logger.warning(
                f"Neo4j adapter not available - cannot increment substance metric for {ku_uid}"
            )

    # ========================================================================
    # ADDITIONAL API METHODS - Required by knowledge_api.py
    # ========================================================================

    async def get_knowledge_prerequisites(self, uid: str) -> Result[list[KuDTO]]:
        """
        Get prerequisite knowledge units (API-compatible wrapper).

        Args:
            uid: Knowledge unit UID

        Returns:
            Result with list of prerequisite knowledge units
        """
        return await self.get_prerequisites(uid)

    async def find_related_knowledge(
        self, uid: str, similarity_threshold: float = 0.7, limit: int = 10
    ) -> Result[list[KuDTO]]:
        """
        Find knowledge units related to the given unit.

        Args:
            uid: Knowledge unit UID
            similarity_threshold: Minimum similarity score
            limit: Maximum results

        Returns:
            Result with list of related knowledge units
        """
        # Get semantic neighborhood which includes related knowledge
        neighborhood_result = await self.semantic.get_semantic_neighborhood(
            uid=uid, depth=2, min_confidence=similarity_threshold
        )

        if neighborhood_result.is_error:
            return Result.fail(neighborhood_result.expect_error())

        # Extract related UIDs from neighborhood
        neighborhood = neighborhood_result.value
        related_uids = []

        if isinstance(neighborhood, dict):
            # Extract UIDs from neighborhood structure
            for nodes in neighborhood.values():
                if isinstance(nodes, list):
                    for node in nodes[:limit]:
                        if isinstance(node, dict) and "uid" in node:
                            related_uids.append(node["uid"])
                        elif isinstance(node, HasUID):
                            related_uids.append(node.uid)

        # Fetch full KuDTO objects
        kus = []
        for ku_uid in related_uids[:limit]:
            ku_result = await self.core.get(ku_uid)
            if ku_result.is_ok and ku_result.value:
                kus.append(ku_result.value)

        return Result.ok(kus)

    async def get_knowledge_recommendations(
        self,
        uid: str,
        user_uid: str | None = None,
        recommendation_type: str = "learning",
    ) -> Result[list[KuDTO]]:
        """
        Get personalized knowledge recommendations.

        Args:
            uid: Starting knowledge unit UID
            user_uid: Optional user for personalization
            recommendation_type: Type of recommendation ("learning", "related", "next")

        Returns:
            Result with list of recommended knowledge units
        """
        if recommendation_type == "next":
            # Get next steps in learning path
            return await self.graph.find_next_steps(uid=uid, limit=5)
        elif recommendation_type == "related":
            # Get related knowledge
            return await self.find_related_knowledge(uid, limit=10)
        else:
            # Default: learning recommendations starting from the given uid
            # Note: get_learning_recommendations is user-global, so for uid-specific
            # recommendations we use find_next_steps which traverses from the starting point
            return await self.graph.find_next_steps(uid=uid, limit=10)

    async def list_knowledge_domains(self) -> Result[list[str]]:
        """
        List all knowledge domains.

        Returns:
            Result with list of unique domain names
        """
        from core.models.enums import Domain

        # Return all domain enum values
        domains = [d.value for d in Domain]
        return Result.ok(domains)

    async def list_knowledge_categories(self) -> Result[list[str]]:
        """
        List all knowledge categories.

        Returns:
            Result with list of unique categories
        """
        if not self.repo:
            return Result.fail(
                Errors.system(
                    message="Knowledge repository not available",
                    operation="list_knowledge_categories",
                )
            )

        # Get all knowledge units and extract unique categories
        result = await self.repo.list(QueryLimit.COMPREHENSIVE)

        if result.is_error:
            return Result.fail(result.expect_error())

        kus, _ = result.value
        categories = set()
        for ku in kus:
            if ku.sel_category:
                categories.add(ku.sel_category)

        return Result.ok(sorted(list(categories)))

    async def list_knowledge_tags(self, min_usage: int = 1) -> Result[list[dict[str, Any]]]:
        """
        List all knowledge tags with usage counts.

        Args:
            min_usage: Minimum usage count to include tag

        Returns:
            Result with list of tag dictionaries (tag, count)
        """
        if not self.repo:
            return Result.fail(
                Errors.system(
                    message="Knowledge repository not available",
                    operation="list_knowledge_tags",
                )
            )

        # Get all knowledge units and count tag usage
        result = await self.repo.list(QueryLimit.COMPREHENSIVE)

        if result.is_error:
            return Result.fail(result.expect_error())

        kus, _ = result.value
        tag_counts: dict[str, int] = {}
        for ku in kus:
            if ku.tags:
                for tag in ku.tags:
                    tag_counts[tag] = tag_counts.get(tag, 0) + 1

        # Filter by min_usage and format (sorted descending by count)
        tags_list = [
            {"tag": tag, "count": count}
            for tag, count in sorted(tag_counts.items(), key=get_second_item, reverse=True)
            if count >= min_usage
        ]

        return Result.ok(tags_list)

    async def get_knowledge_stats(self, uid: str) -> Result[dict[str, Any]]:
        """
        Get statistics for a knowledge unit.

        Args:
            uid: Knowledge unit UID

        Returns:
            Result with statistics dictionary
        """
        # Get the knowledge unit
        ku_result = await self.core.get(uid)
        if ku_result.is_error:
            return Result.fail(ku_result.expect_error())

        ku = ku_result.value
        if not ku:
            return Result.fail(Errors.not_found(resource="Ku", identifier=uid))

        # Get prerequisites count
        prereqs_result = await self.get_prerequisites(uid)
        prereq_count = len(prereqs_result.value) if prereqs_result.is_ok else 0

        # Get dependents count
        deps_result = await self.get_knowledge_dependencies(uid)
        deps_count = len(deps_result.value) if deps_result.is_ok else 0

        stats = {
            "uid": uid,
            "title": ku.title,
            "domain": ku.domain.value if ku.domain else None,
            "content_length": len(ku.content or ""),
            "tag_count": len(ku.tags or []),
            "prerequisite_count": prereq_count,
            "dependent_count": deps_count,
            "created_at": ku.created_at.isoformat() if ku.created_at else None,
            "updated_at": ku.updated_at.isoformat() if ku.updated_at else None,
        }

        return Result.ok(stats)

    # ========================================================================
    # USER CONTEXT OPERATIONS - KU-Activity Integration (January 2026)
    # ========================================================================

    async def get_user_knowledge_context(
        self, ku_uid: str, user_context: "UserContext"
    ) -> Result[dict[str, Any]]:
        """
        Get personalized KU context showing how a user applies this knowledge.

        Calculates per-user substance score based on their activity domains
        (tasks, habits, events, journals, choices) that reference this KU.

        Args:
            ku_uid: Knowledge Unit identifier
            user_context: UserContext with user's activity data

        Returns:
            Result with personalized context including:
            - user_substance_score: 0.0-1.0 (how much user has applied knowledge)
            - global_substance_score: 0.0-1.0 (how much all users have applied)
            - breakdown: counts per activity type with entity UIDs
            - mastery_level: user's mastery of this KU
            - recommendations: personalized next steps
            - status_message: human-readable status

        Example response:
            {
                "ku_uid": "ku.python-basics",
                "user_substance_score": 0.45,
                "breakdown": {
                    "tasks": {"count": 3, "uids": [...], "score": 0.15},
                    "habits": {"count": 1, "uids": [...], "score": 0.10},
                    ...
                },
                "recommendations": [
                    {"type": "journal", "message": "Reflect on...", "impact": "+0.07"}
                ]
            }
        """
        return await self.intelligence.calculate_user_substance(ku_uid, user_context)
