"""Insight Card Component
=======================

UI component for displaying event-driven insights with actions.

Used in the /insights dashboard to show active insights generated by
intelligence services based on user behavior patterns.
"""

from fasthtml.common import Button, Div, Form, H3, Li, NotStr, P, Span, Ul

from core.models.insight.persisted_insight import PersistedInsight
from ui.primitives.badge import Badge
from ui.primitives.card import Card
from ui.primitives.layout import FlexItem, Row
from ui.primitives.text import CardTitle, SmallText, TruncatedText


def InsightCard(insight: PersistedInsight) -> Div:
    """Render a single insight with dismiss/action buttons.

    Args:
        insight: PersistedInsight model with all insight data

    Returns:
        Card component displaying the insight

    Example:
        insight = PersistedInsight(
            uid="insight.difficulty_pattern.habit_meditation_abc123.20260131",
            user_uid="user_mike",
            insight_type=InsightType.DIFFICULTY_PATTERN,
            domain="habits",
            title="Daily Meditation: Difficulty Detected",
            description="You've missed this habit 5 times in a row.",
            confidence=0.85,
            impact=InsightImpact.HIGH,
            entity_uid="habit_meditation_abc123",
            recommended_actions=[{"action": "Reduce frequency", "rationale": "Build momentum"}],
        )
        InsightCard(insight)
    """
    # Impact badge colors (maps to priority colors)
    impact_colors = {
        "critical": "border-l-error",
        "high": "border-l-error",
        "medium": "border-l-warning",
        "low": "border-l-success",
    }
    border_cls = impact_colors.get(insight.impact.value, "border-l-base-300")

    # Build badges row
    badges = []

    # Impact badge (uses priority badge styling)
    impact_badge = Badge(
        insight.impact.value.upper(),
        variant="error"
        if insight.impact.value in ("critical", "high")
        else "warning"
        if insight.impact.value == "medium"
        else "success",
    )
    badges.append(impact_badge)

    # Domain badge
    domain_badge = Badge(insight.domain, variant="neutral")
    badges.append(domain_badge)

    # Confidence badge
    confidence_pct = int(insight.confidence * 100)
    confidence_badge = Badge(f"{confidence_pct}% confident", variant="ghost")
    badges.append(confidence_badge)

    badge_row = Row(*badges, gap=2)

    # Header row: title + badges
    header = Row(
        FlexItem(CardTitle(insight.title, truncate=True), grow=True),
        FlexItem(badge_row, shrink=False),
        gap=3,
    )

    # Content list
    content = [header]

    # Description
    if insight.description:
        content.append(
            TruncatedText(
                insight.description,
                lines=3,
                cls="text-sm text-base-content/70 mt-2 block",
            )
        )

    # Recommended actions (if any)
    if insight.recommended_actions:
        action_items = []
        for action_dict in insight.recommended_actions[:3]:  # Limit to 3 actions
            action_text = action_dict.get("action", "")
            rationale = action_dict.get("rationale", "")
            if action_text:
                action_html = f"<strong>{action_text}</strong>"
                if rationale:
                    action_html += f": {rationale}"
                action_items.append(
                    Div(
                        NotStr(
                            f'<span class="text-xs text-base-content/80">• {action_html}</span>'
                        ),
                        cls="mt-1",
                    )
                )

        if action_items:
            content.append(
                Div(
                    SmallText("Recommended Actions:", cls="font-semibold mb-1"),
                    *action_items,
                    cls="mt-3 p-3 bg-base-200 rounded-md",
                )
            )

    # Action buttons (Dismiss, Mark as Actioned, and View Entity)
    # Phase 2, Task 10: Responsive button sizing - btn-md on mobile, btn-sm on desktop
    # Phase 3, Task 11: Add "View Entity" link for deep linking to profile
    action_buttons_list = [
        Form(
            Button(
                "Dismiss",
                cls="btn btn-md md:btn-sm btn-ghost",  # btn-md on mobile (<768px), btn-sm on desktop
                hx_post=f"/api/insights/{insight.uid}/dismiss",
                hx_target=f"#insight-{insight.uid}",
                hx_swap="outerHTML swap:1s",
            ),
            hx_confirm="Dismiss this insight? You won't see it again.",
        ),
        Form(
            Button(
                "I've Acted on This",
                cls="btn btn-md md:btn-sm btn-primary",  # btn-md on mobile, btn-sm on desktop
                hx_post=f"/api/insights/{insight.uid}/action",
                hx_target=f"#insight-{insight.uid}",
                hx_swap="outerHTML swap:1s",
            ),
            hx_confirm="Mark this insight as actioned?",
        ),
    ]

    # Add "View Entity" button if entity_uid exists (Phase 3, Task 11)
    if insight.entity_uid:
        from fasthtml.common import A

        action_buttons_list.append(
            A(
                Button(
                    "View Entity",
                    cls="btn btn-md md:btn-sm btn-ghost",
                ),
                href=f"/profile/{insight.domain}?focus={insight.entity_uid}",
            )
        )

    # Add "View Details" button for modal (Phase 3, Task 13)
    action_buttons_list.insert(
        0,  # Insert at beginning
        Button(
            "View Details",
            cls="btn btn-md md:btn-sm btn-ghost",
            x_on_click="open()",
        ),
    )

    action_buttons = Div(
        *action_buttons_list,
        cls="flex flex-col md:flex-row gap-2",  # Stack vertically on mobile, horizontal on desktop
    )

    content.append(Div(action_buttons, cls="mt-4 pt-3 border-t border-base-200"))

    # Card with impact-based border
    # Phase 3, Task 13: Wrap in Alpine component for modal
    card = Card(
        *content,
        cls=f"border-l-4 {border_cls}",
        id=f"insight-{insight.uid}",  # For HTMX targeting
    )

    # Wrap card and modal in Alpine controller
    return Div(
        card,
        InsightDetailModal(insight),  # Add modal component
        x_data=f"insightDetailModal('{insight.uid}')",
    )


def InsightMiniCard(insight: PersistedInsight, show_domain: bool = False) -> Div:
    """Render a compact insight card for embedding in profile views.

    Args:
        insight: PersistedInsight model
        show_domain: Whether to show domain badge (useful when embedding in overview)

    Returns:
        Compact card component for profile hub integration

    Example:
        # In profile habits view
        InsightMiniCard(habit_insight, show_domain=False)

        # In profile overview
        InsightMiniCard(insight, show_domain=True)
    """
    # Impact indicator dot
    impact_colors = {
        "critical": "bg-error",
        "high": "bg-error",
        "medium": "bg-warning",
        "low": "bg-success",
    }
    dot_color = impact_colors.get(insight.impact.value, "bg-base-300")

    # Build badge
    badges = []
    impact_badge = Badge(
        insight.impact.value.upper(),
        variant="error"
        if insight.impact.value in ("critical", "high")
        else "warning"
        if insight.impact.value == "medium"
        else "success",
    )
    badges.append(impact_badge)

    if show_domain:
        domain_badge = Badge(insight.domain, variant="neutral")
        badges.append(domain_badge)

    # Phase 3, Task 11: Deep linking - determine link URL based on entity_uid
    # If entity_uid exists, deep link to profile with focus parameter
    # Otherwise, fall back to filtered insights page
    link_url = (
        f"/profile/{insight.domain}?focus={insight.entity_uid}"
        if insight.entity_uid
        else f"/insights?domain={insight.domain}"
    )
    button_text = "View in Profile" if insight.entity_uid else "View Details"

    # Compact layout - single row with title, badges, and link
    return Div(
        Div(
            # Impact dot indicator
            Div(cls=f"size-2 rounded-full {dot_color} flex-shrink-0"),
            # Title (truncated)
            TruncatedText(
                insight.title,
                lines=1,
                cls="text-sm font-medium text-base-content flex-grow",
            ),
            # Badges
            Row(*badges, gap=1),
            cls="flex items-center gap-3",
        ),
        # Description (truncated to 1 line)
        TruncatedText(
            insight.description or "",
            lines=1,
            cls="text-xs text-base-content/60 mt-1 block",
        ),
        # Link button
        Div(
            Button(
                button_text,
                cls="btn btn-xs btn-ghost",
                hx_get=link_url,
                hx_boost="false",
            ),
            cls="mt-2",
        ),
        cls="p-3 bg-base-200 rounded-lg border-l-2 border-l-warning cursor-pointer hover:bg-base-300 transition-colors",
        hx_get=link_url,
        hx_boost="false",
    )


def DismissedInsightMessage() -> Div:
    """Message shown when an insight is dismissed."""
    return Div(
        Div(
            NotStr("✓ Insight dismissed"),
            cls="alert alert-success",
        ),
        cls="mb-4",
    )


def InsightDetailModal(insight: PersistedInsight) -> Div:
    """Modal dialog for viewing detailed insight information (Phase 3, Task 13).

    Shows:
    - Full description and supporting data
    - Confidence breakdown with visual indicator
    - Related entities
    - Recommended actions with rationale
    - Snooze functionality

    Args:
        insight: PersistedInsight model with all insight data

    Returns:
        DaisyUI modal component wrapped in Alpine.js controller
    """
    # Build confidence indicator
    confidence_pct = int(insight.confidence * 100)
    if confidence_pct >= 80:
        confidence_color = "text-success"
        confidence_label = "High Confidence"
    elif confidence_pct >= 60:
        confidence_color = "text-warning"
        confidence_label = "Medium Confidence"
    else:
        confidence_color = "text-error"
        confidence_label = "Low Confidence"

    # Build supporting data section
    supporting_data_items = []
    if hasattr(insight, "metadata") and insight.metadata:
        # Extract supporting data from metadata
        supporting_data = insight.metadata.get("supporting_data", {})
        if supporting_data:
            for key, value in supporting_data.items():
                supporting_data_items.append(
                    Li(
                        Span(f"{key.replace('_', ' ').title()}: ", cls="font-semibold"),
                        Span(str(value), cls="text-base-content/70"),
                        cls="py-1",
                    )
                )

    supporting_section = Div()
    if supporting_data_items:
        supporting_section = Div(
            H3("Supporting Data", cls="text-lg font-semibold text-base-content mb-3"),
            Ul(*supporting_data_items, cls="space-y-1"),
            cls="mb-6",
        )

    # Build recommended actions section (with full rationale)
    actions_section = Div()
    if insight.recommended_actions:
        action_items = []
        for action_dict in insight.recommended_actions:
            action_text = action_dict.get("action", "")
            rationale = action_dict.get("rationale", "")
            if action_text:
                action_items.append(
                    Li(
                        Div(
                            Span(action_text, cls="font-semibold text-base-content"),
                            cls="mb-1",
                        ),
                        Div(
                            Span(rationale, cls="text-sm text-base-content/70"),
                            cls="ml-4",
                        ) if rationale else Div(),
                        cls="mb-3",
                    )
                )

        if action_items:
            actions_section = Div(
                H3("Recommended Actions", cls="text-lg font-semibold text-base-content mb-3"),
                Ul(*action_items, cls="space-y-2"),
                cls="mb-6",
            )

    # Modal structure (DaisyUI modal)
    return Div(
        # Modal overlay
        Div(
            # Modal box
            Div(
                # Close button
                Button(
                    "✕",
                    cls="btn btn-sm btn-circle btn-ghost absolute right-2 top-2",
                    x_on_click="close()",
                ),
                # Modal header
                Div(
                    H3(insight.title, cls="text-2xl font-bold text-base-content"),
                    Div(
                        Badge(
                            insight.impact.value.upper(),
                            variant="error" if insight.impact.value in ("critical", "high")
                            else "warning" if insight.impact.value == "medium"
                            else "success",
                        ),
                        Badge(insight.domain, variant="neutral"),
                        cls="flex gap-2 mt-2",
                    ),
                    cls="mb-6",
                ),
                # Confidence indicator
                Div(
                    Span("Confidence: ", cls="font-semibold text-base-content"),
                    Span(f"{confidence_pct}%", cls=f"font-bold {confidence_color}"),
                    Span(f" ({confidence_label})", cls="text-sm text-base-content/60 ml-2"),
                    cls="mb-4 p-3 bg-base-200 rounded-lg",
                ),
                # Full description
                Div(
                    H3("Details", cls="text-lg font-semibold text-base-content mb-3"),
                    P(insight.description or "No additional details available.", cls="text-base-content/80"),
                    cls="mb-6",
                ),
                # Supporting data (if available)
                supporting_section,
                # Recommended actions
                actions_section,
                # Entity info
                Div(
                    Span("Related Entity: ", cls="font-semibold text-base-content"),
                    Span(insight.entity_uid or "None", cls="text-sm text-base-content/60 font-mono"),
                    cls="mb-6 text-sm",
                ) if insight.entity_uid else Div(),
                # Action buttons
                Div(
                    # Snooze options
                    Div(
                        Span("Snooze for:", cls="text-sm font-medium text-base-content mr-3"),
                        Button("1 Day", cls="btn btn-sm btn-ghost", x_on_click="snooze(1)"),
                        Button("3 Days", cls="btn btn-sm btn-ghost", x_on_click="snooze(3)"),
                        Button("1 Week", cls="btn btn-sm btn-ghost", x_on_click="snooze(7)"),
                        cls="flex items-center gap-2",
                    ),
                    # Close button
                    Button(
                        "Close",
                        cls="btn btn-primary",
                        x_on_click="close()",
                    ),
                    cls="flex items-center justify-between pt-4 border-t border-base-200",
                ),
                cls="modal-box max-w-2xl max-h-[80vh] overflow-y-auto",
            ),
            cls="modal-backdrop",
            x_on_click="close()",
        ),
        cls="modal",
        x_show="isOpen",
        x_cloak=True,
    )
