"""Insight Card Component
=======================

UI component for displaying event-driven insights with actions.

Used in the /insights dashboard to show active insights generated by
intelligence services based on user behavior patterns.
"""

from typing import Any

from fasthtml.common import Button, Div, Form, NotStr

from core.models.insight.persisted_insight import PersistedInsight
from ui.primitives.badge import Badge
from ui.primitives.card import Card
from ui.primitives.layout import FlexItem, Row
from ui.primitives.text import CardTitle, SmallText, TruncatedText


def InsightCard(insight: PersistedInsight) -> Div:
    """Render a single insight with dismiss/action buttons.

    Args:
        insight: PersistedInsight model with all insight data

    Returns:
        Card component displaying the insight

    Example:
        insight = PersistedInsight(
            uid="insight.difficulty_pattern.habit_meditation_abc123.20260131",
            user_uid="user_mike",
            insight_type=InsightType.DIFFICULTY_PATTERN,
            domain="habits",
            title="Daily Meditation: Difficulty Detected",
            description="You've missed this habit 5 times in a row.",
            confidence=0.85,
            impact=InsightImpact.HIGH,
            entity_uid="habit_meditation_abc123",
            recommended_actions=[{"action": "Reduce frequency", "rationale": "Build momentum"}],
        )
        InsightCard(insight)
    """
    # Impact badge colors (maps to priority colors)
    impact_colors = {
        "critical": "border-l-error",
        "high": "border-l-error",
        "medium": "border-l-warning",
        "low": "border-l-success",
    }
    border_cls = impact_colors.get(insight.impact.value, "border-l-base-300")

    # Build badges row
    badges = []

    # Impact badge (uses priority badge styling)
    impact_badge = Badge(
        insight.impact.value.upper(),
        variant="error"
        if insight.impact.value in ("critical", "high")
        else "warning"
        if insight.impact.value == "medium"
        else "success",
    )
    badges.append(impact_badge)

    # Domain badge
    domain_badge = Badge(insight.domain, variant="neutral")
    badges.append(domain_badge)

    # Confidence badge
    confidence_pct = int(insight.confidence * 100)
    confidence_badge = Badge(f"{confidence_pct}% confident", variant="ghost")
    badges.append(confidence_badge)

    badge_row = Row(*badges, gap=2)

    # Header row: title + badges
    header = Row(
        FlexItem(CardTitle(insight.title, truncate=True), grow=True),
        FlexItem(badge_row, shrink=False),
        gap=3,
    )

    # Content list
    content = [header]

    # Description
    if insight.description:
        content.append(
            TruncatedText(
                insight.description,
                lines=3,
                cls="text-sm text-base-content/70 mt-2 block",
            )
        )

    # Recommended actions (if any)
    if insight.recommended_actions:
        action_items = []
        for action_dict in insight.recommended_actions[:3]:  # Limit to 3 actions
            action_text = action_dict.get("action", "")
            rationale = action_dict.get("rationale", "")
            if action_text:
                action_html = f"<strong>{action_text}</strong>"
                if rationale:
                    action_html += f": {rationale}"
                action_items.append(
                    Div(
                        NotStr(
                            f'<span class="text-xs text-base-content/80">• {action_html}</span>'
                        ),
                        cls="mt-1",
                    )
                )

        if action_items:
            content.append(
                Div(
                    SmallText("Recommended Actions:", cls="font-semibold mb-1"),
                    *action_items,
                    cls="mt-3 p-3 bg-base-200 rounded-md",
                )
            )

    # Action buttons (Dismiss and Mark as Actioned)
    action_buttons = Div(
        Form(
            Button(
                "Dismiss",
                cls="btn btn-sm btn-ghost",
                hx_post=f"/api/insights/{insight.uid}/dismiss",
                hx_target=f"#insight-{insight.uid}",
                hx_swap="outerHTML swap:1s",
            ),
            hx_confirm="Dismiss this insight? You won't see it again.",
        ),
        Form(
            Button(
                "I've Acted on This",
                cls="btn btn-sm btn-primary",
                hx_post=f"/api/insights/{insight.uid}/action",
                hx_target=f"#insight-{insight.uid}",
                hx_swap="outerHTML swap:1s",
            ),
            hx_confirm="Mark this insight as actioned?",
        ),
        cls="flex gap-2",
    )

    content.append(Div(action_buttons, cls="mt-4 pt-3 border-t border-base-200"))

    # Card with impact-based border
    return Card(
        *content,
        cls=f"border-l-4 {border_cls}",
        id=f"insight-{insight.uid}",  # For HTMX targeting
    )


def DismissedInsightMessage() -> Div:
    """Message shown when an insight is dismissed."""
    return Div(
        Div(
            NotStr("✓ Insight dismissed"),
            cls="alert alert-success",
        ),
        cls="mb-4",
    )
