"""Insight Card Component
=======================

UI component for displaying event-driven insights with actions.

Used in the /insights dashboard to show active insights generated by
intelligence services based on user behavior patterns.
"""

from typing import Any

from fasthtml.common import H3, Div, Form, Li, P, Span, Strong, Ul

from core.models.insight.persisted_insight import InsightImpact, PersistedInsight
from ui.components import Button, ButtonT
from ui.feedback import Alert, AlertT, Badge, BadgeT
from ui.layout import Row
from ui.patterns.card_generator import CardGenerator
from ui.patterns.modal import AlpineModal
from ui.primitives import ButtonLink


def _render_description(desc: str) -> Any:
    return Span(desc, cls="line-clamp-3 text-sm text-muted-foreground mt-2 block")


def InsightCard(insight: PersistedInsight) -> Div:
    """Render a single insight with dismiss/action buttons.

    Args:
        insight: PersistedInsight model with all insight data

    Returns:
        Card component displaying the insight

    Example:
        insight = PersistedInsight(
            uid="insight.difficulty_pattern.habit_meditation_abc123.20260131",
            user_uid="user_mike",
            insight_type=InsightType.DIFFICULTY_PATTERN,
            domain="habits",
            title="Daily Meditation: Difficulty Detected",
            description="You've missed this habit 5 times in a row.",
            confidence=0.85,
            impact=InsightImpact.HIGH,
            entity_uid="habit_meditation_abc123",
            recommended_actions=[{"action": "Reduce frequency", "rationale": "Build momentum"}],
        )
        InsightCard(insight)
    """
    # Impact badge colors (maps to priority colors)
    from ui.enum_helpers import get_priority_border_class

    border_cls = get_priority_border_class(insight.impact.value)

    # Build badges
    impact_variant = (
        BadgeT.error
        if insight.impact in (InsightImpact.CRITICAL, InsightImpact.HIGH)
        else BadgeT.warning
        if insight.impact == InsightImpact.MEDIUM
        else BadgeT.success
    )
    impact_badge = Badge(insight.impact.value.upper(), variant=impact_variant)
    domain_badge = Badge(insight.domain, variant=BadgeT.neutral)
    confidence_pct = int(insight.confidence * 100)
    confidence_badge = Badge(f"{confidence_pct}% confident", variant=BadgeT.ghost)

    # Recommended actions metadata
    actions_metadata: list[Any] = []
    if insight.recommended_actions:
        action_items = []
        for action_dict in insight.recommended_actions[:3]:
            action_text = action_dict.get("action", "")
            rationale = action_dict.get("rationale", "")
            if action_text:
                action_items.append(
                    Div(
                        Span(
                            "• ",
                            Strong(f"{action_text!s}"),
                            f": {rationale!s}" if rationale else "",
                            cls="text-xs text-foreground/80",
                        ),
                        cls="mt-1",
                    )
                )
        if action_items:
            actions_metadata.append(
                Div(
                    Span(
                        "Recommended Actions:",
                        cls="text-sm text-muted-foreground font-semibold mb-1",
                    ),
                    *action_items,
                    cls="mt-3 p-3 bg-muted rounded-md",
                )
            )

    # Action buttons
    action_buttons_list: list[Any] = [
        Button(
            "View Details",
            cls=ButtonT.ghost,
            size="sm",
            **{"x-on:click": "open()"},  # fasthtml dynamic-attr splat
        ),
        Form(
            Button(
                "Dismiss",
                cls=ButtonT.ghost,
                size="sm",
                hx_post=f"/api/insights/{insight.uid}/dismiss",
                hx_target=f"#insight-{insight.uid}",
                hx_swap="outerHTML swap:1s",
            ),
            hx_confirm="Dismiss this insight? You won't see it again.",
        ),
        Form(
            Button(
                "I've Acted on This",
                cls=ButtonT.primary,
                size="sm",
                hx_post=f"/api/insights/{insight.uid}/action",
                hx_target=f"#insight-{insight.uid}",
                hx_swap="outerHTML swap:1s",
            ),
            hx_confirm="Mark this insight as actioned?",
        ),
    ]
    if insight.entity_uid:
        action_buttons_list.append(
            ButtonLink(
                "View Entity",
                href=f"/profile/{insight.domain}?focus={insight.entity_uid}",
                cls=ButtonT.ghost,
                size="sm",
            )
        )

    action_buttons_div = Div(
        *action_buttons_list,
        cls="flex flex-col md:flex-row gap-2",
    )

    # Build card via CardGenerator
    card = CardGenerator.from_dataclass(
        {"title": insight.title, "description": insight.description or ""},
        display_fields=["description"],
        field_renderers={
            "description": _render_description,
        },
        header_badges=[impact_badge, domain_badge, confidence_badge],
        show_labels=False,
        metadata=actions_metadata if actions_metadata else None,
        actions=action_buttons_div,
        card_attrs={
            "cls": f"border-l-4 {border_cls}",
            "id": f"insight-{insight.uid}",
        },
    )

    # Wrap card and modal in Alpine controller
    return Div(
        card,
        InsightDetailModal(insight),
        x_data=f"insightDetailModal('{insight.uid}')",
    )


def InsightMiniCard(insight: PersistedInsight, show_domain: bool = False) -> Div:
    """Render a compact insight card for embedding in profile views.

    Args:
        insight: PersistedInsight model
        show_domain: Whether to show domain badge (useful when embedding in overview)

    Returns:
        Compact card component for profile hub integration

    Example:
        # In profile habits view
        InsightMiniCard(habit_insight, show_domain=False)

        # In profile overview
        InsightMiniCard(insight, show_domain=True)
    """
    # Impact indicator dot
    from ui.enum_helpers import get_priority_dot_class

    dot_color = get_priority_dot_class(insight.impact.value)

    # Build badge
    badges = []
    impact_variant = (
        BadgeT.error
        if insight.impact in (InsightImpact.CRITICAL, InsightImpact.HIGH)
        else BadgeT.warning
        if insight.impact == InsightImpact.MEDIUM
        else BadgeT.success
    )
    impact_badge = Badge(insight.impact.value.upper(), variant=impact_variant)
    badges.append(impact_badge)

    if show_domain:
        domain_badge = Badge(insight.domain, variant=BadgeT.neutral)
        badges.append(domain_badge)

    # Determine link URL based on entity_uid
    # If entity_uid exists, deep link to profile with focus parameter
    # Otherwise, fall back to filtered insights page
    link_url = (
        f"/profile/{insight.domain}?focus={insight.entity_uid}"
        if insight.entity_uid
        else f"/insights?domain={insight.domain}"
    )
    button_text = "View in Profile" if insight.entity_uid else "View Details"

    # Compact layout - single row with title, badges, and link
    return Div(
        Div(
            # Impact dot indicator
            Div(cls=f"size-2 rounded-full {dot_color} shrink-0"),
            # Title (truncated)
            Span(insight.title, cls="line-clamp-1 text-sm font-medium text-foreground grow"),
            # Badges
            Row(*badges, gap=1),
            cls="flex items-center gap-3",
        ),
        # Description (truncated to 1 line)
        Span(
            insight.description or "", cls="line-clamp-1 text-xs text-muted-foreground mt-1 block"
        ),
        # Link button
        Div(
            Button(
                button_text,
                cls=ButtonT.ghost,
                size="xs",
                hx_get=link_url,
            ),
            cls="mt-2",
        ),
        cls="p-3 bg-muted rounded-lg border-l-2 border-l-warning cursor-pointer hover:bg-secondary transition-colors",
        hx_get=link_url,
    )


def DismissedInsightMessage() -> Div:
    """Message shown when an insight is dismissed."""
    return Div(
        Alert(
            "✓ Insight dismissed",
            variant=AlertT.success,
        ),
        cls="mb-4",
    )


def InsightDetailModal(insight: PersistedInsight) -> Div:
    """Modal dialog for viewing detailed insight information.

    Shows:
    - Full description and supporting data
    - Confidence breakdown with visual indicator
    - Related entities
    - Recommended actions with rationale
    - Snooze functionality

    Args:
        insight: PersistedInsight model with all insight data

    Returns:
        Modal component wrapped in Alpine.js controller
    """
    # Build confidence indicator
    confidence_pct = int(insight.confidence * 100)
    if confidence_pct >= 80:
        confidence_color = "text-success"
        confidence_label = "High Confidence"
    elif confidence_pct >= 60:
        confidence_color = "text-warning"
        confidence_label = "Medium Confidence"
    else:
        confidence_color = "text-error"
        confidence_label = "Low Confidence"

    # Build supporting data section
    supporting_data_items = []
    metadata = getattr(insight, "metadata", None)
    if metadata:
        # Extract supporting data from metadata
        supporting_data = metadata.get("supporting_data", {})
        if supporting_data:
            for key, value in supporting_data.items():
                supporting_data_items.append(
                    Li(
                        Span(f"{key.replace('_', ' ').title()}: ", cls="font-semibold"),
                        Span(str(value), cls="text-muted-foreground"),
                        cls="py-1",
                    )
                )

    supporting_section = Div()
    if supporting_data_items:
        supporting_section = Div(
            H3("Supporting Data", cls="text-lg font-semibold text-foreground mb-3"),
            Ul(*supporting_data_items, cls="space-y-1"),
            cls="mb-6",
        )

    # Build recommended actions section (with full rationale)
    actions_section = Div()
    if insight.recommended_actions:
        action_items = []
        for action_dict in insight.recommended_actions:
            action_text = action_dict.get("action", "")
            rationale = action_dict.get("rationale", "")
            if action_text:
                action_items.append(
                    Li(
                        Div(
                            Span(action_text, cls="font-semibold text-foreground"),
                            cls="mb-1",
                        ),
                        Div(
                            Span(rationale, cls="text-sm text-muted-foreground"),
                            cls="ml-4",
                        )
                        if rationale
                        else Div(),
                        cls="mb-3",
                    )
                )

        if action_items:
            actions_section = Div(
                H3("Recommended Actions", cls="text-lg font-semibold text-foreground mb-3"),
                Ul(*action_items, cls="space-y-2"),
                cls="mb-6",
            )

    return AlpineModal(
        # Close button
        Button(
            "✕",
            cls=(ButtonT.ghost, "rounded-full absolute right-2 top-2"),
            size="sm",
            **{"x-on:click": "close()"},  # fasthtml dynamic-attr splat
        ),
        # Modal header
        Div(
            H3(insight.title, cls="text-2xl font-bold text-foreground"),
            Div(
                Badge(
                    insight.impact.value.upper(),
                    variant=BadgeT.error
                    if insight.impact in (InsightImpact.CRITICAL, InsightImpact.HIGH)
                    else BadgeT.warning
                    if insight.impact == InsightImpact.MEDIUM
                    else BadgeT.success,
                ),
                Badge(insight.domain, variant=BadgeT.neutral),
                cls="flex gap-2 mt-2",
            ),
            cls="mb-6",
        ),
        # Confidence indicator
        Div(
            Span("Confidence: ", cls="font-semibold text-foreground"),
            Span(f"{confidence_pct}%", cls=f"font-bold {confidence_color}"),
            Span(f" ({confidence_label})", cls="text-sm text-muted-foreground ml-2"),
            cls="mb-4 p-3 bg-muted rounded-lg",
        ),
        # Full description
        Div(
            H3("Details", cls="text-lg font-semibold text-foreground mb-3"),
            P(
                insight.description or "No additional details available.",
                cls="text-foreground/80",
            ),
            cls="mb-6",
        ),
        # Supporting data (if available)
        supporting_section,
        # Recommended actions
        actions_section,
        # Entity info
        Div(
            Span("Related Entity: ", cls="font-semibold text-foreground"),
            Span(insight.entity_uid or "None", cls="text-sm text-muted-foreground font-mono"),
            cls="mb-6 text-sm",
        )
        if insight.entity_uid
        else Div(),
        # Action buttons
        Div(
            # Snooze options
            Div(
                Span("Snooze for:", cls="text-sm font-medium text-foreground mr-3"),
                Button(
                    "1 Day",
                    cls=ButtonT.ghost,
                    size="sm",
                    **{"x-on:click": "snooze(1)"},  # fasthtml dynamic-attr splat
                ),
                Button(
                    "3 Days",
                    cls=ButtonT.ghost,
                    size="sm",
                    **{"x-on:click": "snooze(3)"},  # fasthtml dynamic-attr splat
                ),
                Button(
                    "1 Week",
                    cls=ButtonT.ghost,
                    size="sm",
                    **{"x-on:click": "snooze(7)"},  # fasthtml dynamic-attr splat
                ),
                cls="flex items-center gap-2",
            ),
            # Close button
            Button(
                "Close",
                cls=ButtonT.primary,
                **{"x-on:click": "close()"},  # fasthtml dynamic-attr splat
            ),
            cls="flex items-center justify-between pt-4 border-t border-border",
        ),
        show="isOpen",
        close="close()",
        max_width="max-w-2xl",
        scrollable=True,
    )
