"""
Password Reset Token Model
==========================

Admin-generated password reset tokens stored as Neo4j nodes.

Design:
- Tokens are generated by admins (no email service required)
- Short-lived (15 minutes by default - industry standard)
- Single-use (consumed by the same write that sets the new password)
- Linked to user via relationship

Neo4j Schema:
    (:PasswordResetToken {
        uid: "reset_{uuid}",
        token: "{secure_token}",
        user_uid: "user_xxx",
        created_at: datetime(),
        expires_at: datetime(),
        is_used: false,
        created_by_admin_uid: "user_admin"
    })

    (user:User)-[:HAS_RESET_TOKEN]->(token:PasswordResetToken)
"""

import secrets
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta

from core.models.type_hints import UserUID

# Token configuration
RESET_TOKEN_BYTES = 32  # 256-bit tokens
RESET_TOKEN_EXPIRY_MINUTES = 15  # 15 minutes validity (industry standard for security)


def generate_reset_token() -> str:
    """Generate a cryptographically secure reset token."""
    return secrets.token_urlsafe(RESET_TOKEN_BYTES)


def generate_reset_token_uid() -> str:
    """Generate a unique reset token UID."""
    return f"reset_{secrets.token_hex(16)}"


@dataclass(frozen=True)
class PasswordResetToken:
    """
    Password reset token stored as Neo4j node.

    Immutable token model following three-tier architecture.

    Attributes:
        uid: Unique token identifier
        token: Secure token value (provided to user; excluded from repr)
        user_uid: User this token is for
        created_at: When token was created
        expires_at: When token expires
        is_used: Whether token has been used
        created_by_admin_uid: Admin who generated this token
    """

    uid: str
    # repr=False: whoever holds this token can reset the password. Keeping it
    # out of repr() keeps it out of log lines, tracebacks and debugger frames.
    token: str = field(repr=False)
    user_uid: UserUID
    created_at: datetime
    expires_at: datetime
    is_used: bool = False
    created_by_admin_uid: str | None = None


@dataclass(frozen=True)
class PasswordResetClaim:
    """Outcome of one attempt to redeem a reset token.

    Validity (unused, unexpired, user still present) is decided by the
    claiming write itself, under the token's write-lock — never by a read
    beforehand. See SessionBackend.reset_password_and_revoke_sessions.

    Attributes:
        claimed: True when this attempt consumed the token and set the password
        user_uid: The token's user (None when the user no longer exists)
        email: That user's email, for the audit event
        revoked_count: Live sessions revoked in the same transaction
    """

    claimed: bool
    user_uid: UserUID | None
    email: str | None
    revoked_count: int


def create_password_reset_token(
    user_uid: UserUID,
    created_by_admin_uid: str | None = None,
    expiry_minutes: int = RESET_TOKEN_EXPIRY_MINUTES,
) -> PasswordResetToken:
    """
    Factory function to create a password reset token.

    Args:
        user_uid: The user this token is for
        created_by_admin_uid: Admin who generated this token
        expiry_minutes: Minutes until token expires (default: 15)

    Returns:
        New PasswordResetToken instance with secure token
    """
    now = datetime.now(UTC)
    return PasswordResetToken(
        uid=generate_reset_token_uid(),
        token=generate_reset_token(),
        user_uid=user_uid,
        created_at=now,
        expires_at=now + timedelta(minutes=expiry_minutes),
        is_used=False,
        created_by_admin_uid=created_by_admin_uid,
    )


__all__ = [
    "RESET_TOKEN_BYTES",
    "RESET_TOKEN_EXPIRY_MINUTES",
    "PasswordResetClaim",
    "PasswordResetToken",
    "create_password_reset_token",
    "generate_reset_token",
    "generate_reset_token_uid",
]
