"""
Password Reset Token Model
==========================

Admin-generated password reset tokens stored as Neo4j nodes.

Design:
- Tokens are generated by admins (no email service required)
- Short-lived (15 minutes by default - industry standard)
- Single-use (marked used after password reset)
- Linked to user via relationship

Neo4j Schema:
    (:PasswordResetToken {
        uid: "reset_{uuid}",
        token: "{secure_token}",
        user_uid: "user_xxx",
        created_at: datetime(),
        expires_at: datetime(),
        is_used: false,
        created_by_admin_uid: "user_admin"
    })

    (user:User)-[:HAS_RESET_TOKEN]->(token:PasswordResetToken)
"""

import secrets
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

# Token configuration
RESET_TOKEN_BYTES = 32  # 256-bit tokens
RESET_TOKEN_EXPIRY_MINUTES = 15  # 15 minutes validity (industry standard for security)


def generate_reset_token() -> str:
    """Generate a cryptographically secure reset token."""
    return secrets.token_urlsafe(RESET_TOKEN_BYTES)


def generate_reset_token_uid() -> str:
    """Generate a unique reset token UID."""
    return f"reset_{secrets.token_hex(16)}"


@dataclass(frozen=True)
class PasswordResetToken:
    """
    Password reset token stored as Neo4j node.

    Immutable token model following three-tier architecture.

    Attributes:
        uid: Unique token identifier
        token: Secure token value (provided to user)
        user_uid: User this token is for
        created_at: When token was created
        expires_at: When token expires
        is_used: Whether token has been used
        created_by_admin_uid: Admin who generated this token
    """

    uid: str
    token: str
    user_uid: str
    created_at: datetime
    expires_at: datetime
    is_used: bool = False
    created_by_admin_uid: str | None = None

    def is_expired(self) -> bool:
        """Check if token has expired."""
        return datetime.now(timezone.utc) > self.expires_at

    def is_valid(self) -> bool:
        """Check if token is valid (not expired and not used)."""
        return not self.is_expired() and not self.is_used

    def time_until_expiry(self) -> timedelta:
        """Get time remaining until expiry."""
        return self.expires_at - datetime.now(timezone.utc)

    def mark_used(self) -> "PasswordResetToken":
        """
        Create used version of this token.

        Since PasswordResetToken is frozen, this returns a new instance.
        """
        return PasswordResetToken(
            uid=self.uid,
            token=self.token,
            user_uid=self.user_uid,
            created_at=self.created_at,
            expires_at=self.expires_at,
            is_used=True,
            created_by_admin_uid=self.created_by_admin_uid,
        )


def create_password_reset_token(
    user_uid: str,
    created_by_admin_uid: str | None = None,
    expiry_minutes: int = RESET_TOKEN_EXPIRY_MINUTES,
) -> PasswordResetToken:
    """
    Factory function to create a password reset token.

    Args:
        user_uid: The user this token is for
        created_by_admin_uid: Admin who generated this token
        expiry_minutes: Minutes until token expires (default: 15)

    Returns:
        New PasswordResetToken instance with secure token
    """
    now = datetime.now(timezone.utc)
    return PasswordResetToken(
        uid=generate_reset_token_uid(),
        token=generate_reset_token(),
        user_uid=user_uid,
        created_at=now,
        expires_at=now + timedelta(minutes=expiry_minutes),
        is_used=False,
        created_by_admin_uid=created_by_admin_uid,
    )


__all__ = [
    "RESET_TOKEN_BYTES",
    "RESET_TOKEN_EXPIRY_MINUTES",
    "PasswordResetToken",
    "create_password_reset_token",
    "generate_reset_token",
    "generate_reset_token_uid",
]
