// Constraints for Vector entities
CREATE CONSTRAINT vector_uid IF NOT EXISTS
FOR (n:Vector) REQUIRE n.uid IS UNIQUE;

CREATE CONSTRAINT state_uid IF NOT EXISTS
FOR (n:State) REQUIRE n.uid IS UNIQUE;

CREATE CONSTRAINT je_uid IF NOT EXISTS
FOR (n:JournalEntry) REQUIRE n.uid IS UNIQUE;

CREATE CONSTRAINT lp_uid IF NOT EXISTS
FOR (n:LifePrinciple) REQUIRE n.uid IS UNIQUE;