"""
Insight Domain Models
=====================

Models for persisted insights generated by event-driven intelligence.

The PersistedInsight model extends the transient AskesisInsight pattern
with persistence fields for Neo4j storage.
"""

from core.models.insight.persisted_insight import (
    InsightImpact,
    InsightType,
    PersistedInsight,
)

__all__ = ["PersistedInsight", "InsightType", "InsightImpact"]
