"""
Insight Domain Models
=====================

Models for insights generated by event-driven and task-derived intelligence.

The PersistedInsight model extends the transient AskesisInsight pattern
with persistence fields for Neo4j storage. The generated_insight models
(TaskPattern, GeneratedInsight, KuQualityMetrics) are transient value
objects for InsightGenerationService's task-to-knowledge pipeline.
"""

from core.models.insight.generated_insight import (
    GeneratedInsight,
    InsightCategory,
    KuQualityMetrics,
    PatternType,
    TaskPattern,
)
from core.models.insight.persisted_insight import (
    InsightImpact,
    InsightType,
    PersistedInsight,
)

__all__ = [
    "GeneratedInsight",
    "InsightCategory",
    "InsightImpact",
    "InsightType",
    "KuQualityMetrics",
    "PatternType",
    "PersistedInsight",
    "TaskPattern",
]
