"""
Persisted Insight Model
=======================

Domain model for insights that are stored in Neo4j for retrieval,
dismissal, and action tracking.

This extends the transient AskesisInsight pattern with:
- Persistence fields (uid, created_at, expires_at)
- Lifecycle fields (dismissed, actioned)
- Graph relationship metadata

Usage:
    insight = PersistedInsight(
        uid="insight.habit-difficulty.20260114",
        user_uid="user.mike",
        insight_type=InsightType.DIFFICULTY_PATTERN,
        domain="habits",
        title="Habit Difficulty Detected",
        description="You've missed 'Daily Meditation' 5 times in the last 14 days.",
        confidence=0.85,
        impact=InsightImpact.MEDIUM,
        entity_uid="habit.meditation",
        recommended_actions=[
            {"action": "Reduce frequency", "rationale": "Build momentum with achievable goals"}
        ],
    )
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any


class InsightType(str, Enum):
    """Types of insights generated by the intelligence system."""

    # Learning Progress
    LEARNING_PROGRESS = "learning_progress"
    MASTERY_ACHIEVED = "mastery_achieved"
    KNOWLEDGE_GAP = "knowledge_gap"

    # Activity Patterns
    DIFFICULTY_PATTERN = "difficulty_pattern"
    STREAK_PATTERN = "streak_pattern"
    COMPLETION_PATTERN = "completion_pattern"

    # Decision Intelligence
    DECISION_PATTERN = "decision_pattern"
    OUTCOME_ANALYSIS = "outcome_analysis"
    PRINCIPLE_ALIGNMENT = "principle_alignment"
    PRINCIPLE_CONFLICT = "principle_conflict"

    # Cross-Domain
    CROSS_DOMAIN_CONNECTION = "cross_domain_connection"
    SYNERGY_OPPORTUNITY = "synergy_opportunity"
    IMBALANCE_DETECTED = "imbalance_detected"

    # Content/Organization
    COVERAGE_ANALYSIS = "coverage_analysis"
    BRIDGE_OPPORTUNITY = "bridge_opportunity"


class InsightImpact(str, Enum):
    """Impact level of an insight for prioritization."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

    def get_priority_score(self) -> int:
        """Get numeric priority for sorting."""
        scores = {
            InsightImpact.LOW: 1,
            InsightImpact.MEDIUM: 2,
            InsightImpact.HIGH: 3,
            InsightImpact.CRITICAL: 4,
        }
        return scores.get(self, 0)


@dataclass(frozen=True)
class PersistedInsight:
    """
    A persisted insight stored in Neo4j.

    Insights are generated by event handlers and aggregators, then stored
    for later retrieval through the InsightStore API.

    Lifecycle:
    - Created: Generated by event handler or aggregator
    - Active: Visible to user in insights feed
    - Dismissed: User marked as not relevant
    - Actioned: User took action based on insight
    - Expired: Past expires_at timestamp (auto-cleaned)

    Graph Storage:
    - Node label: Insight
    - Relationships:
        - (User)-[:HAS_INSIGHT]->(Insight)
        - (Insight)-[:ABOUT_ENTITY]->(Entity)
        - (Insight)-[:RELATES_TO]->(Entity) (for related_entities)

    Attributes:
        uid: Unique identifier (format: insight.{type}.{timestamp})
        user_uid: Owner of this insight
        insight_type: Category of insight
        domain: Source domain (e.g., "habits", "choices", "ku")
        title: Short summary for display
        description: Detailed explanation
        confidence: How confident we are (0.0-1.0)
        impact: Priority level for sorting
        entity_uid: Primary entity this insight is about
        related_entities: Other entities involved by type
        recommended_actions: Suggested next steps
        supporting_data: Raw data that generated this insight
        created_at: When insight was generated
        expires_at: When insight should be auto-deleted (None = never)
        dismissed: User dismissed this insight
        actioned: User took action on this insight
    """

    uid: str
    user_uid: str
    insight_type: InsightType
    domain: str
    title: str
    description: str
    confidence: float
    impact: InsightImpact
    entity_uid: str
    created_at: datetime = field(default_factory=datetime.now)

    # Related entities grouped by type: {"goals": ["goal.1", "goal.2"], "tasks": ["task.1"]}
    related_entities: dict[str, list[str]] = field(default_factory=dict)

    # Actions with structure: [{"action": "Do X", "rationale": "Because Y"}]
    recommended_actions: list[dict[str, Any]] = field(default_factory=list)

    # Supporting data that generated this insight (for debugging/audit)
    supporting_data: dict[str, Any] = field(default_factory=dict)

    # Expiration (None = never expires)
    expires_at: datetime | None = None

    # Lifecycle flags
    dismissed: bool = False
    actioned: bool = False

    # Action tracking
    dismissed_at: datetime | None = None
    dismissed_notes: str = ""
    actioned_at: datetime | None = None
    actioned_notes: str = ""

    def __post_init__(self) -> None:
        """Validate insight on creation."""
        if not self.uid:
            raise ValueError("Insight uid is required")
        if not self.user_uid:
            raise ValueError("Insight user_uid is required")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be 0.0-1.0, got {self.confidence}")

    @classmethod
    def generate_uid(cls, insight_type: InsightType, entity_uid: str) -> str:
        """
        Generate a unique insight UID.

        Format: insight.{type}.{entity_slug}.{timestamp}

        Args:
            insight_type: Type of insight
            entity_uid: Primary entity this insight is about

        Returns:
            Unique insight UID
        """
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        entity_slug = entity_uid.replace(".", "-").replace(":", "-")[:20]
        return f"insight.{insight_type.value}.{entity_slug}.{timestamp}"

    @classmethod
    def with_default_expiry(
        cls,
        days: int = 30,
        **kwargs: Any,
    ) -> "PersistedInsight":
        """
        Create insight with default expiry.

        Args:
            days: Days until expiry (default 30)
            **kwargs: Other insight fields

        Returns:
            PersistedInsight with expires_at set
        """
        expires_at = datetime.now() + timedelta(days=days)
        return cls(expires_at=expires_at, **kwargs)

    def is_expired(self) -> bool:
        """Check if insight has expired."""
        if self.expires_at is None:
            return False
        return datetime.now() > self.expires_at

    def is_active(self) -> bool:
        """Check if insight should be shown to user."""
        return not self.dismissed and not self.actioned and not self.is_expired()

    def priority_score(self) -> float:
        """
        Calculate priority score for sorting.

        Higher score = higher priority.
        Factors: impact level, confidence, recency
        """
        impact_score = self.impact.get_priority_score()
        recency_hours = (datetime.now() - self.created_at).total_seconds() / 3600
        recency_factor = max(0.5, 1.0 - (recency_hours / 168))  # Decay over 1 week
        return impact_score * self.confidence * recency_factor

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "uid": self.uid,
            "user_uid": self.user_uid,
            "insight_type": self.insight_type.value,
            "domain": self.domain,
            "title": self.title,
            "description": self.description,
            "confidence": self.confidence,
            "impact": self.impact.value,
            "entity_uid": self.entity_uid,
            "related_entities": self.related_entities,
            "recommended_actions": self.recommended_actions,
            "supporting_data": self.supporting_data,
            "created_at": self.created_at.isoformat(),
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "dismissed": self.dismissed,
            "actioned": self.actioned,
            "dismissed_at": self.dismissed_at.isoformat() if self.dismissed_at else None,
            "dismissed_notes": self.dismissed_notes,
            "actioned_at": self.actioned_at.isoformat() if self.actioned_at else None,
            "actioned_notes": self.actioned_notes,
            "is_active": self.is_active(),
            "priority_score": self.priority_score(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PersistedInsight":
        """Create from dictionary."""
        # Parse datetime fields
        created_at = data.get("created_at")
        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)
        elif created_at is None:
            created_at = datetime.now()

        expires_at = data.get("expires_at")
        if isinstance(expires_at, str):
            expires_at = datetime.fromisoformat(expires_at)

        # Parse action tracking timestamps
        dismissed_at = data.get("dismissed_at")
        if isinstance(dismissed_at, str):
            dismissed_at = datetime.fromisoformat(dismissed_at)

        actioned_at = data.get("actioned_at")
        if isinstance(actioned_at, str):
            actioned_at = datetime.fromisoformat(actioned_at)

        # Parse enum fields
        insight_type = data.get("insight_type")
        if isinstance(insight_type, str):
            insight_type = InsightType(insight_type)

        impact = data.get("impact")
        if isinstance(impact, str):
            impact = InsightImpact(impact)

        return cls(
            uid=data["uid"],
            user_uid=data["user_uid"],
            insight_type=insight_type,
            domain=data.get("domain", "unknown"),
            title=data.get("title", ""),
            description=data.get("description", ""),
            confidence=data.get("confidence", 0.5),
            impact=impact,
            entity_uid=data.get("entity_uid", ""),
            related_entities=data.get("related_entities", {}),
            recommended_actions=data.get("recommended_actions", []),
            supporting_data=data.get("supporting_data", {}),
            created_at=created_at,
            expires_at=expires_at,
            dismissed=data.get("dismissed", False),
            actioned=data.get("actioned", False),
            dismissed_at=dismissed_at,
            dismissed_notes=data.get("dismissed_notes", ""),
            actioned_at=actioned_at,
            actioned_notes=data.get("actioned_notes", ""),
        )
