"""
Analytics Domain Models
=======================

Three-tier type system for statistical analytics:
- Tier 1 (External): Pydantic models in analytics_report_request.py
- Tier 2 (Transfer): AnalyticsSummaryDTO - Mutable data transfer
- Tier 3 (Core): AnalyticsSummary - Frozen domain model

Analytics are purely statistical assessments generated BY the system FOR the user.
They contain quantitative metrics (completion rates, totals, averages) without
AI-generated recommendations or prescriptive guidance.
"""

from dataclasses import dataclass, field
from datetime import date, datetime
from enum import Enum
from typing import Any

from core.models.shared_enums import AnalyticsDomain

# ============================================================================
# TIER 2 - DTO (Transfer Layer)
# ============================================================================


@dataclass
class AnalyticsSummaryDTO:
    """
    Mutable data transfer object for analytics summaries.

    Used for:
    - Moving data between service and persistence layers
    - Constructing analytics summaries before freezing into domain models
    - Database serialization/deserialization
    """

    uid: str
    user_uid: str
    analytics_domain: AnalyticsDomain
    period_start: date
    period_end: date
    metrics: dict[str, Any]
    generated_at: datetime
    title: str | None = None
    markdown_content: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage"""
        return {
            "uid": self.uid,
            "user_uid": self.user_uid,
            "analytics_domain": self.analytics_domain.value
            if isinstance(self.analytics_domain, Enum)
            else self.analytics_domain,
            "period_start": self.period_start.isoformat(),
            "period_end": self.period_end.isoformat(),
            "metrics": self.metrics,
            "generated_at": self.generated_at.isoformat(),
            "title": self.title,
            "markdown_content": self.markdown_content,
            "metadata": self.metadata,
        }


# ============================================================================
# TIER 3 - Domain Model (Core Business Logic)
# ============================================================================


@dataclass(frozen=True)
class AnalyticsSummary:
    """
    Immutable domain model for statistical analytics.

    An analytics summary is a quantitative assessment of user data within a specific
    domain (tasks, habits, goals, etc.) over a defined time period.

    Analytics contain ONLY statistical metrics - no AI recommendations or
    prescriptive guidance. SKUEL listens and responds; it doesn't push advice.

    Examples:
    - Task completion rate: 87% (13 of 15 tasks completed)
    - Habit consistency: 6 days/week average
    - Goal progress: 3 on track, 1 at risk
    - Finance: $2,450 expenses across 8 categories
    """

    uid: str
    user_uid: str
    analytics_domain: AnalyticsDomain
    period_start: date
    period_end: date
    metrics: dict[str, Any]
    generated_at: datetime
    title: str
    markdown_content: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def get_metric(self, key: str, default: Any = None) -> Any:
        """Safely retrieve a metric value"""
        return self.metrics.get(key, default)

    def get_period_days(self) -> int:
        """Calculate number of days in analytics period"""
        return (self.period_end - self.period_start).days + 1

    def is_current_period(self) -> bool:
        """Check if analytics covers current time period"""
        today = date.today()
        return self.period_start <= today <= self.period_end

    def format_period(self) -> str:
        """Format period as human-readable string"""
        if self.period_start.year != self.period_end.year:
            return f"{self.period_start.strftime('%b %d, %Y')} - {self.period_end.strftime('%b %d, %Y')}"
        elif self.period_start.month != self.period_end.month:
            return (
                f"{self.period_start.strftime('%b %d')} - {self.period_end.strftime('%b %d, %Y')}"
            )
        else:
            return f"{self.period_start.strftime('%b %d')} - {self.period_end.strftime('%d, %Y')}"


# ============================================================================
# CONVERSION FUNCTIONS
# ============================================================================


def dto_to_summary(dto: AnalyticsSummaryDTO) -> AnalyticsSummary:
    """Convert DTO to immutable domain model"""
    # Auto-generate title if not provided
    title = (
        dto.title
        or f"{dto.analytics_domain.value.title()} Analytics - {dto.period_start.strftime('%Y-%m-%d')}"
    )

    return AnalyticsSummary(
        uid=dto.uid,
        user_uid=dto.user_uid,
        analytics_domain=dto.analytics_domain,
        period_start=dto.period_start,
        period_end=dto.period_end,
        metrics=dto.metrics.copy(),  # Shallow copy for immutability
        generated_at=dto.generated_at,
        title=title,
        markdown_content=dto.markdown_content or "",
        metadata=dto.metadata.copy(),
    )


def summary_to_dto(summary: AnalyticsSummary) -> AnalyticsSummaryDTO:
    """Convert domain model to mutable DTO"""
    return AnalyticsSummaryDTO(
        uid=summary.uid,
        user_uid=summary.user_uid,
        analytics_domain=summary.analytics_domain,
        period_start=summary.period_start,
        period_end=summary.period_end,
        metrics=dict(summary.metrics),  # Create mutable copy
        generated_at=summary.generated_at,
        title=summary.title,
        markdown_content=summary.markdown_content,
        metadata=dict(summary.metadata),
    )
