"""
Insight Store Service
=====================

Neo4j-backed persistence for event-driven insights.

This service stores insights generated by event handlers and aggregators,
providing APIs for retrieval, dismissal, and action tracking.

Graph Structure:
    (User)-[:HAS_INSIGHT]->(Insight)-[:ABOUT_ENTITY]->(Entity)

The InsightStore follows SKUEL's graph-native philosophy - insights are
first-class graph citizens with relationships to users and entities.

Usage:
    store = InsightStore(backend)

    # Create insight
    result = await store.create_insight(insight)

    # Get active insights for user
    insights = await store.get_active_insights(user_uid)

    # Dismiss or action
    await store.dismiss_insight(uid, user_uid)
    await store.mark_actioned(uid, user_uid)
"""

from typing import TYPE_CHECKING, Any

from core.models.insight.persisted_insight import (
    PersistedInsight,
)
from core.models.type_hints import EntityUID, UserUID
from core.ports.query_types import ChartJsConfig
from core.utils.exception_types import NEO4J_EXCEPTIONS
from core.utils.logging import get_logger
from core.utils.neo4j_props import deserialize_json_fields
from core.utils.result_simplified import Errors, Result

if TYPE_CHECKING:
    from core.ports.insight_protocols import InsightBackendOperations


# Fields stored as JSON strings in Neo4j (dicts/lists that Neo4j can't store natively)
_INSIGHT_JSON_FIELDS = ("related_entities", "recommended_actions", "supporting_data")


class InsightStore:
    """
    Service for persisting and retrieving insights from Neo4j.

    Insights are stored as graph nodes with relationships to users
    and the entities they're about.

    Graph Schema:
        - (:User)-[:HAS_INSIGHT]->(:Insight)
        - (:Insight)-[:ABOUT_ENTITY]->(:Entity)
        - (:Insight {
            uid, user_uid, insight_type, domain, title, description,
            confidence, impact, entity_uid, related_entities (JSON),
            recommended_actions (JSON), supporting_data (JSON),
            created_at, expires_at, dismissed, actioned
          })

    Thread Safety: Each method is atomic - safe for concurrent use.
    """

    def __init__(self, backend: "InsightBackendOperations") -> None:
        """
        Initialize InsightStore with backend.

        Args:
            backend: Insight persistence operations (ADR-044 / SKUEL023 — the
                concrete InsightBackend is built at the composition root and
                satisfies this protocol structurally)
        """
        if not backend:
            raise ValueError(
                "InsightStore backend is REQUIRED. SKUEL follows fail-fast architecture."
            )
        self.backend = backend
        self.logger = get_logger("skuel.services.insight")

    async def create_insight(self, insight: PersistedInsight) -> Result[str]:
        """
        Create a new insight in Neo4j.

        Creates the Insight node and relationships to User and primary entity.

        Args:
            insight: PersistedInsight to persist

        Returns:
            Result with insight UID on success
        """
        try:
            import json

            params = {
                "uid": insight.uid,
                "user_uid": insight.user_uid,
                "insight_type": insight.insight_type.value,
                "domain": insight.domain,
                "title": insight.title,
                "description": insight.description,
                "confidence": insight.confidence,
                "impact": insight.impact.value,
                "entity_uid": insight.entity_uid,
                "related_entities": json.dumps(insight.related_entities),
                "recommended_actions": json.dumps(insight.recommended_actions),
                "supporting_data": json.dumps(insight.supporting_data),
                "created_at": insight.created_at.isoformat(),
                "expires_at": (
                    f"datetime('{insight.expires_at.isoformat()}')" if insight.expires_at else None
                ),
                "dismissed": insight.dismissed,
                "actioned": insight.actioned,
            }

            result = await self.backend.create_insight(params)

            if result.is_error:
                self.logger.error(f"Error creating insight: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to create insight: {result.error}",
                        operation="create_insight",
                    )
                )

            if result.value:
                self.logger.info(
                    f"Created insight: {insight.uid}",
                    extra={
                        "insight_uid": insight.uid,
                        "user_uid": insight.user_uid,
                        "insight_type": insight.insight_type.value,
                        "domain": insight.domain,
                    },
                )
                return Result.ok(insight.uid)

            return Result.fail(
                Errors.database(
                    message="Failed to create insight - no result returned",
                    operation="create_insight",
                )
            )

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Error creating insight: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to create insight: {e}",
                    operation="create_insight",
                )
            )

    async def get_insight_by_uid(self, uid: str) -> Result[PersistedInsight]:
        """Get a single insight by UID.

        Args:
            uid: Insight UID

        Returns:
            Result with the insight or not-found error
        """
        try:
            result = await self.backend.get(uid)

            if result.is_error:
                return Result.fail(
                    Errors.database(
                        message=f"Failed to get insight: {result.error}",
                        operation="get_insight_by_uid",
                    )
                )

            if not result.value:
                return Result.fail(Errors.not_found(resource="Insight", identifier=uid))

            node = result.value[0]["i"]
            insight_data = dict(node) if not isinstance(node, dict) else node
            deserialize_json_fields(insight_data, *_INSIGHT_JSON_FIELDS)

            return Result.ok(PersistedInsight.from_dict(insight_data))

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Database error getting insight {uid}: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight: {e}",
                    operation="get_insight_by_uid",
                )
            )
        except (ValueError, KeyError, TypeError) as e:
            self.logger.error(f"Data conversion error getting insight {uid}: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight: {e}",
                    operation="get_insight_by_uid",
                )
            )

    async def get_active_insights(
        self,
        user_uid: UserUID,
        domain: str | None = None,
        limit: int = 50,
    ) -> Result[list[PersistedInsight]]:
        """
        Get active (non-dismissed, non-actioned, non-expired) insights for a user.

        Args:
            user_uid: User identifier
            domain: Optional filter by domain (e.g., "habits", "choices")
            limit: Maximum insights to return

        Returns:
            Result with list of active insights, sorted by priority
        """
        try:
            result = await self.backend.get_active_insights(user_uid, domain, limit)

            if result.is_error:
                self.logger.error(f"Error getting active insights: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to get active insights: {result.error}",
                        operation="get_active_insights",
                    )
                )

            insights = []
            for record in result.value:
                node = record["i"]
                insight_data = dict(node) if not isinstance(node, dict) else node
                deserialize_json_fields(insight_data, *_INSIGHT_JSON_FIELDS)
                insights.append(PersistedInsight.from_dict(insight_data))

            self.logger.debug(f"Retrieved {len(insights)} active insights for user {user_uid}")
            return Result.ok(insights)

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Database error getting active insights: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get active insights: {e}",
                    operation="get_active_insights",
                )
            )
        except (ValueError, KeyError, TypeError) as e:
            self.logger.error(f"Data conversion error getting active insights: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get active insights: {e}",
                    operation="get_active_insights",
                )
            )

    async def get_insights_for_entity(
        self,
        entity_uid: EntityUID,
        user_uid: UserUID,
        include_dismissed: bool = False,
    ) -> Result[list[PersistedInsight]]:
        """
        Get insights related to a specific entity.

        Args:
            entity_uid: Entity to get insights for
            user_uid: User who owns the insights
            include_dismissed: Include dismissed insights

        Returns:
            Result with list of insights about this entity
        """
        try:
            result = await self.backend.get_insights_for_entity(
                entity_uid, user_uid, include_dismissed
            )

            if result.is_error:
                self.logger.error(f"Error getting insights for entity {entity_uid}: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to get insights for entity: {result.error}",
                        operation="get_insights_for_entity",
                    )
                )

            insights = []
            for record in result.value:
                node = record["i"]
                insight_data = dict(node) if not isinstance(node, dict) else node
                deserialize_json_fields(insight_data, *_INSIGHT_JSON_FIELDS)
                insights.append(PersistedInsight.from_dict(insight_data))

            return Result.ok(insights)

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(
                f"Database error getting insights for entity {entity_uid}: {e}", exc_info=True
            )
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insights for entity: {e}",
                    operation="get_insights_for_entity",
                )
            )
        except (ValueError, KeyError, TypeError) as e:
            self.logger.error(
                f"Data conversion error getting insights for entity {entity_uid}: {e}",
                exc_info=True,
            )
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insights for entity: {e}",
                    operation="get_insights_for_entity",
                )
            )

    async def dismiss_insight(self, uid: str, user_uid: UserUID, notes: str = "") -> Result[None]:
        """
        Mark an insight as dismissed by the user.

        Dismissed insights won't appear in active lists but remain for analytics.

        Args:
            uid: Insight UID
            user_uid: User who owns the insight
            notes: Optional notes explaining why dismissed

        Returns:
            Result indicating success
        """
        try:
            result = await self.backend.dismiss_insight(uid, user_uid, notes)

            if result.is_error:
                self.logger.error(f"Error dismissing insight {uid}: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to dismiss insight: {result.error}",
                        operation="dismiss_insight",
                    )
                )

            if result.value:
                self.logger.info(
                    f"Dismissed insight: {uid}",
                    extra={"insight_uid": uid, "user_uid": user_uid},
                )
                return Result.ok(None)

            return Result.fail(Errors.not_found(resource="Insight", identifier=uid))

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Error dismissing insight {uid}: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to dismiss insight: {e}",
                    operation="dismiss_insight",
                )
            )

    async def mark_actioned(self, uid: str, user_uid: UserUID, notes: str = "") -> Result[None]:
        """
        Mark an insight as actioned by the user.

        Actioned insights indicate the user took the recommended action.

        Args:
            uid: Insight UID
            user_uid: User who owns the insight
            notes: Optional notes describing action taken

        Returns:
            Result indicating success
        """
        try:
            result = await self.backend.mark_actioned(uid, user_uid, notes)

            if result.is_error:
                self.logger.error(f"Error marking insight actioned {uid}: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to mark insight actioned: {result.error}",
                        operation="mark_actioned",
                    )
                )

            if result.value:
                self.logger.info(
                    f"Marked insight as actioned: {uid}",
                    extra={"insight_uid": uid, "user_uid": user_uid},
                )
                return Result.ok(None)

            return Result.fail(Errors.not_found(resource="Insight", identifier=uid))

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Error marking insight actioned {uid}: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to mark insight actioned: {e}",
                    operation="mark_actioned",
                )
            )

    async def cleanup_expired(self) -> Result[int]:
        """
        Delete expired insights from the database.

        Should be called periodically (e.g., daily) to clean up old insights.

        Returns:
            Result with count of deleted insights
        """
        try:
            result = await self.backend.cleanup_expired()

            if result.is_error:
                self.logger.error(f"Error cleaning up expired insights: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to cleanup expired insights: {result.error}",
                        operation="cleanup_expired",
                    )
                )

            if result.value:
                deleted_count = result.value[0]["deleted_count"]
                self.logger.info(f"Cleaned up {deleted_count} expired insights")
                return Result.ok(deleted_count)

            return Result.ok(0)

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Error cleaning up expired insights: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to cleanup expired insights: {e}",
                    operation="cleanup_expired",
                )
            )

    async def get_insight_history(
        self,
        user_uid: UserUID,
        history_type: str = "all",
        limit: int = 50,
    ) -> Result[list[PersistedInsight]]:
        """
        Get dismissed or actioned insights for history page.

        Args:
            user_uid: User's UID
            history_type: Filter type - "dismissed", "actioned", or "all"
            limit: Maximum number of insights to return

        Returns:
            Result containing list of historical insights
        """
        try:
            result = await self.backend.get_insight_history(user_uid, history_type, limit)

            if result.is_error:
                self.logger.error(f"Error getting insight history: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to get insight history: {result.error}",
                        operation="get_insight_history",
                    )
                )

            insights = []
            for record in result.value:
                node_data = record["i"]
                if not isinstance(node_data, dict):
                    node_data = dict(node_data)
                insight = PersistedInsight.from_dict(node_data)
                insights.append(insight)

            self.logger.debug(
                f"Retrieved {len(insights)} historical insights",
                extra={"user_uid": user_uid, "history_type": history_type},
            )
            return Result.ok(insights)

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Database error getting insight history: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight history: {e}",
                    operation="get_insight_history",
                )
            )
        except (ValueError, KeyError, TypeError) as e:
            self.logger.error(f"Data conversion error getting insight history: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight history: {e}",
                    operation="get_insight_history",
                )
            )

    async def get_insight_stats(self, user_uid: UserUID) -> Result[dict[str, Any]]:
        """
        Get statistics about a user's insights.

        Args:
            user_uid: User identifier

        Returns:
            Result with insight statistics
        """
        try:
            result = await self.backend.get_insight_stats(user_uid)

            if result.is_error:
                self.logger.error(f"Error getting insight stats: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to get insight stats: {result.error}",
                        operation="get_insight_stats",
                    )
                )

            if result.value:
                record = result.value[0]
                return Result.ok(
                    {
                        "total_insights": record["total_insights"],
                        "active_insights": record["active_insights"],
                        "dismissed_insights": record["dismissed_insights"],
                        "actioned_insights": record["actioned_insights"],
                        "critical_insights": record["critical_insights"],
                        "high_insights": record["high_insights"],
                        "domains": record["domains"],
                        "action_rate": (
                            record["actioned_insights"] / record["total_insights"]
                            if record["total_insights"] > 0
                            else 0.0
                        ),
                    }
                )

            return Result.ok(
                {
                    "total_insights": 0,
                    "active_insights": 0,
                    "dismissed_insights": 0,
                    "actioned_insights": 0,
                    "critical_insights": 0,
                    "high_insights": 0,
                    "domains": [],
                    "action_rate": 0.0,
                }
            )

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Error getting insight stats: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight stats: {e}",
                    operation="get_insight_stats",
                )
            )

    # ========================================
    # In-Memory Filtering
    # ========================================

    @staticmethod
    def filter_insights(
        insights: list[PersistedInsight],
        *,
        impact: str | None = None,
        insight_type: str | None = None,
        action_status: str | None = None,
        search: str | None = None,
    ) -> list[PersistedInsight]:
        """Apply in-memory filters to a list of insights.

        Used for client-side filtering when all insights are already fetched.

        Args:
            insights: List of insights to filter
            impact: Filter by impact level value (e.g. "high")
            insight_type: Filter by insight type value (e.g. "difficulty_pattern")
            action_status: "actioned" or "unactioned"
            search: Case-insensitive text search in title and description

        Returns:
            Filtered list of insights
        """
        if impact:
            insights = [i for i in insights if i.impact.value == impact]
        if insight_type:
            insights = [i for i in insights if i.insight_type.value == insight_type]
        if action_status == "unactioned":
            insights = [i for i in insights if not i.actioned]
        elif action_status == "actioned":
            insights = [i for i in insights if i.actioned]
        if search:
            search_lower = search.lower()
            insights = [
                i
                for i in insights
                if search_lower in i.title.lower() or search_lower in (i.description or "").lower()
            ]
        return insights

    # ========================================
    # Bulk Operations
    # ========================================

    async def bulk_dismiss(self, uids: list[str], user_uid: UserUID) -> Result[dict[str, Any]]:
        """Dismiss multiple insights, tracking successes and failures.

        Args:
            uids: List of insight UIDs to dismiss
            user_uid: User who owns the insights

        Returns:
            Result with success_count, total_requested, and failed_uids
        """
        success_count = 0
        failed_uids = []

        for uid in uids:
            result = await self.dismiss_insight(uid, user_uid)
            if result.is_error:
                self.logger.error(f"Failed to dismiss insight {uid}: {result.error}")
                failed_uids.append(uid)
            else:
                success_count += 1

        self.logger.info(f"Bulk dismissed {success_count}/{len(uids)} insights for {user_uid}")

        return Result.ok(
            {
                "success_count": success_count,
                "total_requested": len(uids),
                "failed_uids": failed_uids,
            }
        )

    async def bulk_mark_actioned(
        self, uids: list[str], user_uid: UserUID
    ) -> Result[dict[str, Any]]:
        """Mark multiple insights as actioned, tracking successes and failures.

        Args:
            uids: List of insight UIDs to mark as actioned
            user_uid: User who owns the insights

        Returns:
            Result with success_count, total_requested, and failed_uids
        """
        success_count = 0
        failed_uids = []

        for uid in uids:
            result = await self.mark_actioned(uid, user_uid)
            if result.is_error:
                self.logger.error(f"Failed to mark insight {uid} as actioned: {result.error}")
                failed_uids.append(uid)
            else:
                success_count += 1

        self.logger.info(f"Bulk actioned {success_count}/{len(uids)} insights for {user_uid}")

        return Result.ok(
            {
                "success_count": success_count,
                "total_requested": len(uids),
                "failed_uids": failed_uids,
            }
        )

    async def smart_dismiss(
        self, user_uid: UserUID, filter_type: str, filter_value: str
    ) -> Result[dict[str, Any]]:
        """Dismiss all active insights matching a filter criterion.

        Args:
            user_uid: User who owns the insights
            filter_type: Filter field — "impact", "domain", or "type"
            filter_value: Value to match against

        Returns:
            Result with success_count, total_matching, failed_uids, and filter info
        """
        if filter_type not in ("impact", "domain", "type"):
            return Result.fail(Errors.validation(f"Invalid filter_type: {filter_type}"))

        result = await self.get_active_insights(user_uid=user_uid, limit=200)
        if result.is_error:
            return Result.fail(result)

        insights = result.value

        if filter_type == "impact":
            matching = [i for i in insights if i.impact.value == filter_value]
        elif filter_type == "domain":
            matching = [i for i in insights if i.domain == filter_value]
        else:  # type
            matching = [i for i in insights if i.insight_type.value == filter_value]

        success_count = 0
        failed_uids = []

        for insight in matching:
            dismiss_result = await self.dismiss_insight(insight.uid, user_uid)
            if dismiss_result.is_error:
                self.logger.error(
                    f"Failed to dismiss insight {insight.uid}: {dismiss_result.error}"
                )
                failed_uids.append(insight.uid)
            else:
                success_count += 1

        self.logger.info(
            f"Smart dismissed {success_count}/{len(matching)} "
            f"{filter_type}={filter_value} insights for {user_uid}"
        )

        return Result.ok(
            {
                "success_count": success_count,
                "total_matching": len(matching),
                "failed_uids": failed_uids,
                "filter": {
                    "type": filter_type,
                    "value": filter_value,
                },
            }
        )

    # ========================================
    # Chart Data Methods
    # ========================================

    async def get_impact_distribution_chart(self, user_uid: UserUID) -> Result[ChartJsConfig]:
        """Build Chart.js doughnut config for impact distribution.

        Counts active insights per impact level and returns a complete
        Chart.js configuration dict.

        Args:
            user_uid: User identifier

        Returns:
            Result with Chart.js doughnut config
        """
        result = await self.get_active_insights(user_uid=user_uid, limit=200)
        if result.is_error:
            return Result.fail(result)

        insights = result.value

        impact_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
        for insight in insights:
            impact_counts[insight.impact.value] += 1

        return Result.ok(
            {
                "type": "doughnut",
                "data": {
                    "labels": ["Critical", "High", "Medium", "Low"],
                    "datasets": [
                        {
                            "label": "Insights by Impact",
                            "data": [
                                impact_counts["critical"],
                                impact_counts["high"],
                                impact_counts["medium"],
                                impact_counts["low"],
                            ],
                            "backgroundColor": [
                                "rgba(220, 38, 38, 0.8)",
                                "rgba(234, 88, 12, 0.8)",
                                "rgba(250, 204, 21, 0.8)",
                                "rgba(34, 197, 94, 0.8)",
                            ],
                        }
                    ],
                },
                "options": {
                    "responsive": True,
                    "plugins": {
                        "legend": {"position": "bottom"},
                        "title": {"display": True, "text": "Insights by Impact Level"},
                    },
                },
            }
        )

    async def get_domain_distribution_chart(self, user_uid: UserUID) -> Result[ChartJsConfig]:
        """Build Chart.js bar config for insights by domain.

        Counts active insights per domain, sorted by count descending.

        Args:
            user_uid: User identifier

        Returns:
            Result with Chart.js bar config
        """
        from operator import itemgetter

        result = await self.get_active_insights(user_uid=user_uid, limit=200)
        if result.is_error:
            return Result.fail(result)

        insights = result.value

        domain_counts: dict[str, int] = {}
        for insight in insights:
            domain = insight.domain
            domain_counts[domain] = domain_counts.get(domain, 0) + 1

        sorted_domains = sorted(domain_counts.items(), key=itemgetter(1), reverse=True)

        return Result.ok(
            {
                "type": "bar",
                "data": {
                    "labels": [domain.title() for domain, _ in sorted_domains],
                    "datasets": [
                        {
                            "label": "Active Insights",
                            "data": [count for _, count in sorted_domains],
                            "backgroundColor": "rgba(59, 130, 246, 0.8)",
                        }
                    ],
                },
                "options": {
                    "responsive": True,
                    "plugins": {
                        "legend": {"display": False},
                        "title": {"display": True, "text": "Insights by Domain"},
                    },
                    "scales": {"y": {"beginAtZero": True, "ticks": {"stepSize": 1}}},
                },
            }
        )

    async def get_type_distribution_chart(self, user_uid: UserUID) -> Result[ChartJsConfig]:
        """Build Chart.js doughnut config for insight type distribution.

        Counts active insights per type, sorted by count descending.

        Args:
            user_uid: User identifier

        Returns:
            Result with Chart.js doughnut config
        """
        from operator import itemgetter

        result = await self.get_active_insights(user_uid=user_uid, limit=200)
        if result.is_error:
            return Result.fail(result)

        insights = result.value

        type_counts: dict[str, int] = {}
        for insight in insights:
            insight_type = insight.insight_type.value
            type_counts[insight_type] = type_counts.get(insight_type, 0) + 1

        sorted_types = sorted(type_counts.items(), key=itemgetter(1), reverse=True)
        labels = [t.replace("_", " ").title() for t, _ in sorted_types]

        return Result.ok(
            {
                "type": "doughnut",
                "data": {
                    "labels": labels,
                    "datasets": [
                        {
                            "label": "Insights by Type",
                            "data": [count for _, count in sorted_types],
                            "backgroundColor": [
                                "rgba(99, 102, 241, 0.8)",
                                "rgba(139, 92, 246, 0.8)",
                                "rgba(168, 85, 247, 0.8)",
                                "rgba(236, 72, 153, 0.8)",
                                "rgba(244, 63, 94, 0.8)",
                                "rgba(59, 130, 246, 0.8)",
                            ],
                        }
                    ],
                },
                "options": {
                    "responsive": True,
                    "plugins": {
                        "legend": {"position": "right"},
                        "title": {"display": True, "text": "Insights by Type"},
                    },
                },
            }
        )

    async def get_action_rate_chart(self, user_uid: UserUID) -> Result[ChartJsConfig]:
        """Build Chart.js gauge-style doughnut config for action rate.

        Uses insight stats to show percentage of actioned vs not actioned.

        Args:
            user_uid: User identifier

        Returns:
            Result with Chart.js doughnut config (half-circle gauge)
        """
        stats_result = await self.get_insight_stats(user_uid)
        if stats_result.is_error:
            return Result.fail(stats_result)

        stats = stats_result.value
        action_rate = stats.get("action_rate", 0) * 100
        remaining_rate = 100 - action_rate

        return Result.ok(
            {
                "type": "doughnut",
                "data": {
                    "labels": ["Actioned", "Not Actioned"],
                    "datasets": [
                        {
                            "label": "Action Rate",
                            "data": [action_rate, remaining_rate],
                            "backgroundColor": [
                                "rgba(34, 197, 94, 0.8)",
                                "rgba(156, 163, 175, 0.3)",
                            ],
                        }
                    ],
                },
                "options": {
                    "responsive": True,
                    "circumference": 180,
                    "rotation": -90,
                    "plugins": {
                        "legend": {"position": "bottom"},
                        "title": {"display": True, "text": f"Action Rate: {action_rate:.1f}%"},
                    },
                },
            }
        )

    async def get_insight_counts_by_domain(
        self,
        user_uid: UserUID,
    ) -> Result[dict[str, int]]:
        """
        Get count of active insights grouped by domain.

        Used for Profile Hub integration to show insight badges on domain cards.

        Args:
            user_uid: User identifier

        Returns:
            Result with dict mapping domain -> count (e.g., {"habits": 3, "tasks": 5})

        Example:
            counts = await store.get_insight_counts_by_domain("user_mike")
            # {"habits": 3, "tasks": 5, "goals": 1}
        """
        try:
            result = await self.backend.get_insight_counts_by_domain(user_uid)

            if result.is_error:
                self.logger.error(f"Error getting insight counts by domain: {result.error}")
                return Result.fail(
                    Errors.database(
                        message=f"Failed to get insight counts by domain: {result.error}",
                        operation="get_insight_counts_by_domain",
                    )
                )

            # Build domain -> count dict
            domain_counts: dict[str, int] = {}
            for record in result.value:
                domain = record["domain"]
                count = record["count"]
                domain_counts[domain] = count

            self.logger.debug(f"Retrieved insight counts for user {user_uid}: {domain_counts}")
            return Result.ok(domain_counts)

        except NEO4J_EXCEPTIONS as e:
            self.logger.error(f"Error getting insight counts by domain: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight counts by domain: {e}",
                    operation="get_insight_counts_by_domain",
                )
            )
