"""
Insight Store Service
=====================

Neo4j-backed persistence for event-driven insights.

This service stores insights generated by event handlers and aggregators,
providing APIs for retrieval, dismissal, and action tracking.

Graph Structure:
    (User)-[:HAS_INSIGHT]->(Insight)-[:ABOUT_ENTITY]->(Entity)

The InsightStore follows SKUEL's graph-native philosophy - insights are
first-class graph citizens with relationships to users and entities.

Usage:
    store = InsightStore(driver)

    # Create insight
    result = await store.create_insight(insight)

    # Get active insights for user
    insights = await store.get_active_insights(user_uid)

    # Dismiss or action
    await store.dismiss_insight(uid, user_uid)
    await store.mark_actioned(uid, user_uid)
"""

from typing import TYPE_CHECKING, Any

from core.models.insight.persisted_insight import (
    PersistedInsight,
)
from core.utils.logging import get_logger
from core.utils.result_simplified import Errors, Result

if TYPE_CHECKING:
    from neo4j import AsyncDriver


class InsightStore:
    """
    Service for persisting and retrieving insights from Neo4j.

    Insights are stored as graph nodes with relationships to users
    and the entities they're about.

    Graph Schema:
        - (:User)-[:HAS_INSIGHT]->(:Insight)
        - (:Insight)-[:ABOUT_ENTITY]->(:Entity)
        - (:Insight {
            uid, user_uid, insight_type, domain, title, description,
            confidence, impact, entity_uid, related_entities (JSON),
            recommended_actions (JSON), supporting_data (JSON),
            created_at, expires_at, dismissed, actioned
          })

    Thread Safety: Each method is atomic - safe for concurrent use.
    """

    def __init__(self, driver: "AsyncDriver") -> None:
        """
        Initialize InsightStore with Neo4j driver.

        Args:
            driver: Neo4j async driver for database operations
        """
        if not driver:
            raise ValueError(
                "InsightStore driver is REQUIRED. SKUEL follows fail-fast architecture."
            )
        self.driver = driver
        self.logger = get_logger("skuel.services.insight")

    async def create_insight(self, insight: PersistedInsight) -> Result[str]:
        """
        Create a new insight in Neo4j.

        Creates the Insight node and relationships to User and primary entity.

        Args:
            insight: PersistedInsight to persist

        Returns:
            Result with insight UID on success
        """
        try:
            import json

            query = """
            // Create the Insight node
            CREATE (i:Insight {
                uid: $uid,
                user_uid: $user_uid,
                insight_type: $insight_type,
                domain: $domain,
                title: $title,
                description: $description,
                confidence: $confidence,
                impact: $impact,
                entity_uid: $entity_uid,
                related_entities: $related_entities,
                recommended_actions: $recommended_actions,
                supporting_data: $supporting_data,
                created_at: datetime($created_at),
                expires_at: $expires_at,
                dismissed: $dismissed,
                actioned: $actioned
            })

            // Create relationship to User
            WITH i
            MATCH (u:User {uid: $user_uid})
            CREATE (u)-[:HAS_INSIGHT]->(i)

            // Create relationship to primary entity if it exists
            WITH i
            OPTIONAL MATCH (e {uid: $entity_uid})
            FOREACH (_ IN CASE WHEN e IS NOT NULL THEN [1] ELSE [] END |
                CREATE (i)-[:ABOUT_ENTITY]->(e)
            )

            RETURN i.uid as uid
            """

            params = {
                "uid": insight.uid,
                "user_uid": insight.user_uid,
                "insight_type": insight.insight_type.value,
                "domain": insight.domain,
                "title": insight.title,
                "description": insight.description,
                "confidence": insight.confidence,
                "impact": insight.impact.value,
                "entity_uid": insight.entity_uid,
                "related_entities": json.dumps(insight.related_entities),
                "recommended_actions": json.dumps(insight.recommended_actions),
                "supporting_data": json.dumps(insight.supporting_data),
                "created_at": insight.created_at.isoformat(),
                "expires_at": (
                    f"datetime('{insight.expires_at.isoformat()}')" if insight.expires_at else None
                ),
                "dismissed": insight.dismissed,
                "actioned": insight.actioned,
            }

            result = await self.driver.execute_query(query, params)

            if result.records:
                self.logger.info(
                    f"Created insight: {insight.uid}",
                    extra={
                        "insight_uid": insight.uid,
                        "user_uid": insight.user_uid,
                        "insight_type": insight.insight_type.value,
                        "domain": insight.domain,
                    },
                )
                return Result.ok(insight.uid)

            return Result.fail(
                Errors.database(
                    message="Failed to create insight - no result returned",
                    operation="create_insight",
                )
            )

        except Exception as e:
            self.logger.error(f"Error creating insight: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to create insight: {e}",
                    operation="create_insight",
                )
            )

    async def get_active_insights(
        self,
        user_uid: str,
        domain: str | None = None,
        limit: int = 50,
    ) -> Result[list[PersistedInsight]]:
        """
        Get active (non-dismissed, non-actioned, non-expired) insights for a user.

        Args:
            user_uid: User identifier
            domain: Optional filter by domain (e.g., "habits", "choices")
            limit: Maximum insights to return

        Returns:
            Result with list of active insights, sorted by priority
        """
        try:
            import json

            domain_filter = "AND i.domain = $domain" if domain else ""

            query = f"""
            MATCH (u:User {{uid: $user_uid}})-[:HAS_INSIGHT]->(i:Insight)
            WHERE i.dismissed = false
              AND i.actioned = false
              AND (i.expires_at IS NULL OR i.expires_at > datetime())
              {domain_filter}
            RETURN i
            ORDER BY
                CASE i.impact
                    WHEN 'critical' THEN 4
                    WHEN 'high' THEN 3
                    WHEN 'medium' THEN 2
                    ELSE 1
                END DESC,
                i.confidence DESC,
                i.created_at DESC
            LIMIT $limit
            """

            params: dict[str, Any] = {
                "user_uid": user_uid,
                "limit": limit,
            }
            if domain:
                params["domain"] = domain

            result = await self.driver.execute_query(query, params)

            insights = []
            for record in result.records:
                node = record["i"]
                insight_data = dict(node)

                # Parse JSON fields
                if isinstance(insight_data.get("related_entities"), str):
                    insight_data["related_entities"] = json.loads(insight_data["related_entities"])
                if isinstance(insight_data.get("recommended_actions"), str):
                    insight_data["recommended_actions"] = json.loads(
                        insight_data["recommended_actions"]
                    )
                if isinstance(insight_data.get("supporting_data"), str):
                    insight_data["supporting_data"] = json.loads(insight_data["supporting_data"])

                insights.append(PersistedInsight.from_dict(insight_data))

            self.logger.debug(f"Retrieved {len(insights)} active insights for user {user_uid}")
            return Result.ok(insights)

        except Exception as e:
            self.logger.error(f"Error getting active insights: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get active insights: {e}",
                    operation="get_active_insights",
                )
            )

    async def get_insights_for_entity(
        self,
        entity_uid: str,
        user_uid: str,
        include_dismissed: bool = False,
    ) -> Result[list[PersistedInsight]]:
        """
        Get insights related to a specific entity.

        Args:
            entity_uid: Entity to get insights for
            user_uid: User who owns the insights
            include_dismissed: Include dismissed insights

        Returns:
            Result with list of insights about this entity
        """
        try:
            import json

            dismissed_filter = "" if include_dismissed else "AND i.dismissed = false"

            query = f"""
            MATCH (i:Insight {{entity_uid: $entity_uid, user_uid: $user_uid}})
            WHERE i.actioned = false
              AND (i.expires_at IS NULL OR i.expires_at > datetime())
              {dismissed_filter}
            RETURN i
            ORDER BY i.created_at DESC
            """

            params = {
                "entity_uid": entity_uid,
                "user_uid": user_uid,
            }

            result = await self.driver.execute_query(query, params)

            insights = []
            for record in result.records:
                node = record["i"]
                insight_data = dict(node)

                # Parse JSON fields
                if isinstance(insight_data.get("related_entities"), str):
                    insight_data["related_entities"] = json.loads(insight_data["related_entities"])
                if isinstance(insight_data.get("recommended_actions"), str):
                    insight_data["recommended_actions"] = json.loads(
                        insight_data["recommended_actions"]
                    )
                if isinstance(insight_data.get("supporting_data"), str):
                    insight_data["supporting_data"] = json.loads(insight_data["supporting_data"])

                insights.append(PersistedInsight.from_dict(insight_data))

            return Result.ok(insights)

        except Exception as e:
            self.logger.error(f"Error getting insights for entity {entity_uid}: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insights for entity: {e}",
                    operation="get_insights_for_entity",
                )
            )

    async def dismiss_insight(self, uid: str, user_uid: str, notes: str = "") -> Result[None]:
        """
        Mark an insight as dismissed by the user.

        Dismissed insights won't appear in active lists but remain for analytics.

        Args:
            uid: Insight UID
            user_uid: User who owns the insight
            notes: Optional notes explaining why dismissed (Phase 4, Task 17)

        Returns:
            Result indicating success
        """
        try:
            query = """
            MATCH (i:Insight {uid: $uid, user_uid: $user_uid})
            SET i.dismissed = true,
                i.dismissed_at = datetime(),
                i.dismissed_notes = $notes
            RETURN i.uid as uid
            """

            result = await self.driver.execute_query(
                query, {"uid": uid, "user_uid": user_uid, "notes": notes}
            )

            if result.records:
                self.logger.info(
                    f"Dismissed insight: {uid}",
                    extra={"insight_uid": uid, "user_uid": user_uid},
                )
                return Result.ok(None)

            return Result.fail(Errors.not_found(resource="Insight", identifier=uid))

        except Exception as e:
            self.logger.error(f"Error dismissing insight {uid}: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to dismiss insight: {e}",
                    operation="dismiss_insight",
                )
            )

    async def mark_actioned(self, uid: str, user_uid: str, notes: str = "") -> Result[None]:
        """
        Mark an insight as actioned by the user.

        Actioned insights indicate the user took the recommended action.

        Args:
            uid: Insight UID
            user_uid: User who owns the insight
            notes: Optional notes describing action taken (Phase 4, Task 17)

        Returns:
            Result indicating success
        """
        try:
            query = """
            MATCH (i:Insight {uid: $uid, user_uid: $user_uid})
            SET i.actioned = true,
                i.actioned_at = datetime(),
                i.actioned_notes = $notes
            RETURN i.uid as uid
            """

            result = await self.driver.execute_query(
                query, {"uid": uid, "user_uid": user_uid, "notes": notes}
            )

            if result.records:
                self.logger.info(
                    f"Marked insight as actioned: {uid}",
                    extra={"insight_uid": uid, "user_uid": user_uid},
                )
                return Result.ok(None)

            return Result.fail(Errors.not_found(resource="Insight", identifier=uid))

        except Exception as e:
            self.logger.error(f"Error marking insight actioned {uid}: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to mark insight actioned: {e}",
                    operation="mark_actioned",
                )
            )

    async def cleanup_expired(self) -> Result[int]:
        """
        Delete expired insights from the database.

        Should be called periodically (e.g., daily) to clean up old insights.

        Returns:
            Result with count of deleted insights
        """
        try:
            query = """
            MATCH (i:Insight)
            WHERE i.expires_at IS NOT NULL AND i.expires_at < datetime()
            DETACH DELETE i
            RETURN count(i) as deleted_count
            """

            result = await self.driver.execute_query(query)

            if result.records:
                deleted_count = result.records[0]["deleted_count"]
                self.logger.info(f"Cleaned up {deleted_count} expired insights")
                return Result.ok(deleted_count)

            return Result.ok(0)

        except Exception as e:
            self.logger.error(f"Error cleaning up expired insights: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to cleanup expired insights: {e}",
                    operation="cleanup_expired",
                )
            )

    async def get_insight_history(
        self,
        user_uid: str,
        history_type: str = "all",
        limit: int = 50,
    ) -> Result[list[PersistedInsight]]:
        """
        Get dismissed or actioned insights for history page.

        Phase 4, Task 17: Action tracking and audit trail.

        Args:
            user_uid: User's UID
            history_type: Filter type - "dismissed", "actioned", or "all"
            limit: Maximum number of insights to return

        Returns:
            Result containing list of historical insights
        """
        try:
            # Build WHERE clause based on history type
            if history_type == "dismissed":
                where_clause = "AND i.dismissed = true"
            elif history_type == "actioned":
                where_clause = "AND i.actioned = true"
            else:  # "all"
                where_clause = "AND (i.dismissed = true OR i.actioned = true)"

            query = f"""
            MATCH (i:Insight {{user_uid: $user_uid}})
            WHERE true {where_clause}
            RETURN i
            ORDER BY coalesce(i.dismissed_at, i.actioned_at) DESC
            LIMIT $limit
            """

            result = await self.driver.execute_query(
                query,
                {"user_uid": user_uid, "limit": limit},
            )

            insights = []
            for record in result.records:
                node_data = dict(record["i"])
                insight = PersistedInsight.from_dict(node_data)
                insights.append(insight)

            self.logger.debug(
                f"Retrieved {len(insights)} historical insights",
                extra={"user_uid": user_uid, "history_type": history_type},
            )
            return Result.ok(insights)

        except Exception as e:
            self.logger.error(f"Error getting insight history: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight history: {e}",
                    operation="get_insight_history",
                )
            )

    async def get_insight_stats(self, user_uid: str) -> Result[dict[str, Any]]:
        """
        Get statistics about a user's insights.

        Args:
            user_uid: User identifier

        Returns:
            Result with insight statistics
        """
        try:
            query = """
            MATCH (u:User {uid: $user_uid})-[:HAS_INSIGHT]->(i:Insight)
            RETURN
                count(i) as total_insights,
                count(CASE WHEN i.dismissed = false AND i.actioned = false
                           AND (i.expires_at IS NULL OR i.expires_at > datetime())
                      THEN 1 END) as active_insights,
                count(CASE WHEN i.dismissed = true THEN 1 END) as dismissed_insights,
                count(CASE WHEN i.actioned = true THEN 1 END) as actioned_insights,
                count(CASE WHEN i.impact = 'critical' THEN 1 END) as critical_insights,
                count(CASE WHEN i.impact = 'high' THEN 1 END) as high_insights,
                collect(DISTINCT i.domain) as domains
            """

            result = await self.driver.execute_query(query, {"user_uid": user_uid})

            if result.records:
                record = result.records[0]
                return Result.ok(
                    {
                        "total_insights": record["total_insights"],
                        "active_insights": record["active_insights"],
                        "dismissed_insights": record["dismissed_insights"],
                        "actioned_insights": record["actioned_insights"],
                        "critical_insights": record["critical_insights"],
                        "high_insights": record["high_insights"],
                        "domains": record["domains"],
                        "action_rate": (
                            record["actioned_insights"] / record["total_insights"]
                            if record["total_insights"] > 0
                            else 0.0
                        ),
                    }
                )

            return Result.ok(
                {
                    "total_insights": 0,
                    "active_insights": 0,
                    "dismissed_insights": 0,
                    "actioned_insights": 0,
                    "critical_insights": 0,
                    "high_insights": 0,
                    "domains": [],
                    "action_rate": 0.0,
                }
            )

        except Exception as e:
            self.logger.error(f"Error getting insight stats: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight stats: {e}",
                    operation="get_insight_stats",
                )
            )

    async def get_insight_counts_by_domain(
        self,
        user_uid: str,
    ) -> Result[dict[str, int]]:
        """
        Get count of active insights grouped by domain.

        Used for Profile Hub integration to show insight badges on domain cards.

        Args:
            user_uid: User identifier

        Returns:
            Result with dict mapping domain -> count (e.g., {"habits": 3, "tasks": 5})

        Example:
            counts = await store.get_insight_counts_by_domain("user_mike")
            # {"habits": 3, "tasks": 5, "goals": 1}
        """
        try:
            query = """
            MATCH (u:User {uid: $user_uid})-[:HAS_INSIGHT]->(i:Insight)
            WHERE i.dismissed = false
              AND i.actioned = false
              AND (i.expires_at IS NULL OR i.expires_at > datetime())
            RETURN i.domain as domain, count(i) as count
            ORDER BY count DESC
            """

            result = await self.driver.execute_query(query, {"user_uid": user_uid})

            # Build domain -> count dict
            domain_counts: dict[str, int] = {}
            for record in result.records:
                domain = record["domain"]
                count = record["count"]
                domain_counts[domain] = count

            self.logger.debug(f"Retrieved insight counts for user {user_uid}: {domain_counts}")
            return Result.ok(domain_counts)

        except Exception as e:
            self.logger.error(f"Error getting insight counts by domain: {e}", exc_info=True)
            return Result.fail(
                Errors.database(
                    message=f"Failed to get insight counts by domain: {e}",
                    operation="get_insight_counts_by_domain",
                )
            )
