#!/usr/bin/env python3
"""Generate ui/components/_icon_data.py — inline-SVG markup for the lucide icons SKUEL uses.

WHY: SKUEL renders icons server-side as inline ``<svg>`` (see ``ui/components/icon.py``)
instead of shipping lucide's runtime ``createIcons()`` DOM scanner. This script harvests
the icon geometry for *only the names the codebase actually uses* and writes them to a
committed Python module, so the 410 KB lucide JS bundle never reaches the browser.

SOURCE: the vendored UMD bundle ``static/vendor/lucide/lucide.<ver>.min.js`` — the exact
pinned version already in the repo. Its ``icons`` export maps PascalCase names to icon
nodes (``[["path", {"d": "..."}], ...]``). We read it via node (no network, no new dep).
To switch to lucide-static later, change ``_load_icon_nodes()`` to read its ``icons/*.svg``.

USAGE:
    uv run python scripts/gen_icons.py          # regenerate after adding/removing icons

The used-name surface is scanned from the codebase with the same patterns the icons are
authored with (literal ``Icon("...")`` calls, ``"icon": "..."`` kind maps, JS seed maps,
``data-lucide="..."``). Names that don't resolve in the bundle are WARNED and skipped, not
fatal — comment artifacts shouldn't break the build, and ``Icon()`` falls back to a visible
``help-circle`` at runtime for anything missing. Watch the warnings for genuine typos.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

APP_ROOT = Path(__file__).resolve().parent.parent
BUNDLE = next((APP_ROOT / "static/vendor/lucide").glob("lucide.*.min.js"))
OUT = APP_ROOT / "ui/components/_icon_data.py"

# Fallbacks Icon() references directly — always include even if no call site scans them.
SAFELIST = {"help-circle", "circle"}

# (pattern, file globs) — each pattern's first group is a kebab-case icon name.
SCAN_RULES: list[tuple[str, tuple[str, ...]]] = [
    (r'Icon\("([a-z0-9-]+)"', ("ui/**/*.py", "adapters/**/*.py")),
    (r'"icon":\s*"([a-z0-9-]+)"', ("ui/**/*.py", "adapters/**/*.py")),
    # icon="name" / icon='name' — nav configs (SidebarItem, nav_config) pass icon
    # names this way and later render them via Icon(item.icon).
    (r"""icon=["']([a-z0-9-]+)["']""", ("ui/**/*.py", "adapters/**/*.py")),
    (r"icon:\s*'([a-z0-9-]+)'", ("static/**/*.js",)),
    (r'data-lucide="([a-z0-9-]+)"', ("static/**/*.js", "ui/**/*.py")),
]


def _pascal(name: str) -> str:
    """kebab-case -> PascalCase, matching lucide's icons-object keys ('check-circle-2' -> 'CheckCircle2')."""
    return "".join(part[:1].upper() + part[1:] for part in name.split("-"))


def scan_used_names() -> set[str]:
    """Union of icon names referenced anywhere in the codebase, per SCAN_RULES."""
    names: set[str] = set(SAFELIST)
    for pattern, globs in SCAN_RULES:
        rx = re.compile(pattern)
        for glob in globs:
            for path in APP_ROOT.glob(glob):
                if path.is_file():
                    names.update(rx.findall(path.read_text(encoding="utf-8")))
    return names


def load_icon_nodes() -> dict[str, list[list[object]]]:
    """Read every icon node from the vendored UMD bundle via node (PascalCase keys)."""
    script = f"const l=require({json.dumps(str(BUNDLE))});process.stdout.write(JSON.stringify(l.icons));"
    raw = subprocess.run(  # noqa: S603  (trusted local bundle, no user input)
        ["node", "-e", script], capture_output=True, text=True, check=True
    ).stdout
    return json.loads(raw)


def node_to_markup(node: list[list[object]]) -> str:
    """[['path', {'d': '...'}], ...] -> '<path d="..."/><circle .../>' (leaf children only)."""
    parts: list[str] = []
    for child in node:
        if len(child) > 2:
            raise ValueError(f"nested icon child not supported: {child!r}")
        tag = child[0]
        attrs: dict[str, str] = child[1] if len(child) > 1 else {}  # type: ignore[assignment]
        attr_str = "".join(
            f' {k}="{str(v).replace("&", "&amp;").replace(chr(34), "&quot;")}"'
            for k, v in attrs.items()
        )
        parts.append(f"<{tag}{attr_str}/>")
    return "".join(parts)


def main() -> int:
    used = scan_used_names()
    all_nodes = load_icon_nodes()

    resolved: dict[str, str] = {}
    missing: list[str] = []
    for name in sorted(used):
        node = all_nodes.get(_pascal(name))
        if node is None:
            missing.append(name)
            continue
        resolved[name] = node_to_markup(node)

    if missing:
        print(f"⚠ {len(missing)} used name(s) not in bundle (skipped): {', '.join(missing)}", file=sys.stderr)

    body = "".join(f"    {name!r}: {markup!r},\n" for name, markup in resolved.items())
    OUT.write_text(
        f'"""Inner SVG markup per lucide icon. GENERATED by scripts/gen_icons.py — do not edit.\n\n'
        f"Source: {BUNDLE.name}. Run ``uv run python scripts/gen_icons.py`` to regenerate.\n"
        f'"""\n\n'
        f"ICON_PATHS: dict[str, str] = {{\n{body}}}\n",
        encoding="utf-8",
    )
    print(f"✓ wrote {OUT.relative_to(APP_ROOT)} with {len(resolved)} icons")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
